// Generated by gencpp from file warehouse_sorting_msgs/ArmCommand.msg
// DO NOT EDIT!


#ifndef WAREHOUSE_SORTING_MSGS_MESSAGE_ARMCOMMAND_H
#define WAREHOUSE_SORTING_MSGS_MESSAGE_ARMCOMMAND_H

#include <ros/service_traits.h>


#include <warehouse_sorting_msgs/ArmCommandRequest.h>
#include <warehouse_sorting_msgs/ArmCommandResponse.h>


namespace warehouse_sorting_msgs
{

struct ArmCommand
{

typedef ArmCommandRequest Request;
typedef ArmCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ArmCommand
} // namespace warehouse_sorting_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::warehouse_sorting_msgs::ArmCommand > {
  static const char* value()
  {
    return "3846e631ba5aa8597f045fd2ffbc2e9a";
  }

  static const char* value(const ::warehouse_sorting_msgs::ArmCommand&) { return value(); }
};

template<>
struct DataType< ::warehouse_sorting_msgs::ArmCommand > {
  static const char* value()
  {
    return "warehouse_sorting_msgs/ArmCommand";
  }

  static const char* value(const ::warehouse_sorting_msgs::ArmCommand&) { return value(); }
};


// service_traits::MD5Sum< ::warehouse_sorting_msgs::ArmCommandRequest> should match
// service_traits::MD5Sum< ::warehouse_sorting_msgs::ArmCommand >
template<>
struct MD5Sum< ::warehouse_sorting_msgs::ArmCommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::warehouse_sorting_msgs::ArmCommand >::value();
  }
  static const char* value(const ::warehouse_sorting_msgs::ArmCommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::warehouse_sorting_msgs::ArmCommandRequest> should match
// service_traits::DataType< ::warehouse_sorting_msgs::ArmCommand >
template<>
struct DataType< ::warehouse_sorting_msgs::ArmCommandRequest>
{
  static const char* value()
  {
    return DataType< ::warehouse_sorting_msgs::ArmCommand >::value();
  }
  static const char* value(const ::warehouse_sorting_msgs::ArmCommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::warehouse_sorting_msgs::ArmCommandResponse> should match
// service_traits::MD5Sum< ::warehouse_sorting_msgs::ArmCommand >
template<>
struct MD5Sum< ::warehouse_sorting_msgs::ArmCommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::warehouse_sorting_msgs::ArmCommand >::value();
  }
  static const char* value(const ::warehouse_sorting_msgs::ArmCommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::warehouse_sorting_msgs::ArmCommandResponse> should match
// service_traits::DataType< ::warehouse_sorting_msgs::ArmCommand >
template<>
struct DataType< ::warehouse_sorting_msgs::ArmCommandResponse>
{
  static const char* value()
  {
    return DataType< ::warehouse_sorting_msgs::ArmCommand >::value();
  }
  static const char* value(const ::warehouse_sorting_msgs::ArmCommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAREHOUSE_SORTING_MSGS_MESSAGE_ARMCOMMAND_H
