// Generated by gencpp from file warehouse_sorting_msgs/ArmCommandResponse.msg
// DO NOT EDIT!


#ifndef WAREHOUSE_SORTING_MSGS_MESSAGE_ARMCOMMANDRESPONSE_H
#define WAREHOUSE_SORTING_MSGS_MESSAGE_ARMCOMMANDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace warehouse_sorting_msgs
{
template <class ContainerAllocator>
struct ArmCommandResponse_
{
  typedef ArmCommandResponse_<ContainerAllocator> Type;

  ArmCommandResponse_()
    : success(false)
    , message()  {
    }
  ArmCommandResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::warehouse_sorting_msgs::ArmCommandResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::warehouse_sorting_msgs::ArmCommandResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ArmCommandResponse_

typedef ::warehouse_sorting_msgs::ArmCommandResponse_<std::allocator<void> > ArmCommandResponse;

typedef boost::shared_ptr< ::warehouse_sorting_msgs::ArmCommandResponse > ArmCommandResponsePtr;
typedef boost::shared_ptr< ::warehouse_sorting_msgs::ArmCommandResponse const> ArmCommandResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::warehouse_sorting_msgs::ArmCommandResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::warehouse_sorting_msgs::ArmCommandResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::warehouse_sorting_msgs::ArmCommandResponse_<ContainerAllocator1> & lhs, const ::warehouse_sorting_msgs::ArmCommandResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::warehouse_sorting_msgs::ArmCommandResponse_<ContainerAllocator1> & lhs, const ::warehouse_sorting_msgs::ArmCommandResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace warehouse_sorting_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::warehouse_sorting_msgs::ArmCommandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::warehouse_sorting_msgs::ArmCommandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::warehouse_sorting_msgs::ArmCommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::warehouse_sorting_msgs::ArmCommandResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::warehouse_sorting_msgs::ArmCommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::warehouse_sorting_msgs::ArmCommandResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::warehouse_sorting_msgs::ArmCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::warehouse_sorting_msgs::ArmCommandResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::warehouse_sorting_msgs::ArmCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "warehouse_sorting_msgs/ArmCommandResponse";
  }

  static const char* value(const ::warehouse_sorting_msgs::ArmCommandResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::warehouse_sorting_msgs::ArmCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::warehouse_sorting_msgs::ArmCommandResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::warehouse_sorting_msgs::ArmCommandResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArmCommandResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::warehouse_sorting_msgs::ArmCommandResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::warehouse_sorting_msgs::ArmCommandResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAREHOUSE_SORTING_MSGS_MESSAGE_ARMCOMMANDRESPONSE_H
