// Generated by gencpp from file warehouse_sorting_msgs/DetectedCargoArray.msg
// DO NOT EDIT!


#ifndef WAREHOUSE_SORTING_MSGS_MESSAGE_DETECTEDCARGOARRAY_H
#define WAREHOUSE_SORTING_MSGS_MESSAGE_DETECTEDCARGOARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <warehouse_sorting_msgs/Cargo.h>

namespace warehouse_sorting_msgs
{
template <class ContainerAllocator>
struct DetectedCargoArray_
{
  typedef DetectedCargoArray_<ContainerAllocator> Type;

  DetectedCargoArray_()
    : header()
    , objects()  {
    }
  DetectedCargoArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , objects(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::warehouse_sorting_msgs::Cargo_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::warehouse_sorting_msgs::Cargo_<ContainerAllocator> >> _objects_type;
  _objects_type objects;





  typedef boost::shared_ptr< ::warehouse_sorting_msgs::DetectedCargoArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::warehouse_sorting_msgs::DetectedCargoArray_<ContainerAllocator> const> ConstPtr;

}; // struct DetectedCargoArray_

typedef ::warehouse_sorting_msgs::DetectedCargoArray_<std::allocator<void> > DetectedCargoArray;

typedef boost::shared_ptr< ::warehouse_sorting_msgs::DetectedCargoArray > DetectedCargoArrayPtr;
typedef boost::shared_ptr< ::warehouse_sorting_msgs::DetectedCargoArray const> DetectedCargoArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::warehouse_sorting_msgs::DetectedCargoArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::warehouse_sorting_msgs::DetectedCargoArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::warehouse_sorting_msgs::DetectedCargoArray_<ContainerAllocator1> & lhs, const ::warehouse_sorting_msgs::DetectedCargoArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.objects == rhs.objects;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::warehouse_sorting_msgs::DetectedCargoArray_<ContainerAllocator1> & lhs, const ::warehouse_sorting_msgs::DetectedCargoArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace warehouse_sorting_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::warehouse_sorting_msgs::DetectedCargoArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::warehouse_sorting_msgs::DetectedCargoArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::warehouse_sorting_msgs::DetectedCargoArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::warehouse_sorting_msgs::DetectedCargoArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::warehouse_sorting_msgs::DetectedCargoArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::warehouse_sorting_msgs::DetectedCargoArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::warehouse_sorting_msgs::DetectedCargoArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "753fda52a894cc2e000a484354dd94f2";
  }

  static const char* value(const ::warehouse_sorting_msgs::DetectedCargoArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x753fda52a894cc2eULL;
  static const uint64_t static_value2 = 0x000a484354dd94f2ULL;
};

template<class ContainerAllocator>
struct DataType< ::warehouse_sorting_msgs::DetectedCargoArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "warehouse_sorting_msgs/DetectedCargoArray";
  }

  static const char* value(const ::warehouse_sorting_msgs::DetectedCargoArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::warehouse_sorting_msgs::DetectedCargoArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"warehouse_sorting_msgs/Cargo[] objects\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: warehouse_sorting_msgs/Cargo\n"
"string cargo_id\n"
"string cargo_type\n"
"geometry_msgs/Pose pose\n"
"geometry_msgs/Vector3 size\n"
"float32 volume\n"
"float32 confidence\n"
"int32 bbox_x\n"
"int32 bbox_y\n"
"int32 bbox_width\n"
"int32 bbox_height\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::warehouse_sorting_msgs::DetectedCargoArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::warehouse_sorting_msgs::DetectedCargoArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectedCargoArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::warehouse_sorting_msgs::DetectedCargoArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::warehouse_sorting_msgs::DetectedCargoArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "objects: ";
    if (v.objects.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::warehouse_sorting_msgs::Cargo_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.objects[i]);
    }
    if (v.objects.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAREHOUSE_SORTING_MSGS_MESSAGE_DETECTEDCARGOARRAY_H
