// Generated by gencpp from file warehouse_sorting_msgs/ScanRequestResponse.msg
// DO NOT EDIT!


#ifndef WAREHOUSE_SORTING_MSGS_MESSAGE_SCANREQUESTRESPONSE_H
#define WAREHOUSE_SORTING_MSGS_MESSAGE_SCANREQUESTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <warehouse_sorting_msgs/DetectedCargoArray.h>

namespace warehouse_sorting_msgs
{
template <class ContainerAllocator>
struct ScanRequestResponse_
{
  typedef ScanRequestResponse_<ContainerAllocator> Type;

  ScanRequestResponse_()
    : success(false)
    , message()
    , detections()  {
    }
  ScanRequestResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)
    , detections(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef  ::warehouse_sorting_msgs::DetectedCargoArray_<ContainerAllocator>  _detections_type;
  _detections_type detections;





  typedef boost::shared_ptr< ::warehouse_sorting_msgs::ScanRequestResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::warehouse_sorting_msgs::ScanRequestResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ScanRequestResponse_

typedef ::warehouse_sorting_msgs::ScanRequestResponse_<std::allocator<void> > ScanRequestResponse;

typedef boost::shared_ptr< ::warehouse_sorting_msgs::ScanRequestResponse > ScanRequestResponsePtr;
typedef boost::shared_ptr< ::warehouse_sorting_msgs::ScanRequestResponse const> ScanRequestResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::warehouse_sorting_msgs::ScanRequestResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::warehouse_sorting_msgs::ScanRequestResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::warehouse_sorting_msgs::ScanRequestResponse_<ContainerAllocator1> & lhs, const ::warehouse_sorting_msgs::ScanRequestResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message &&
    lhs.detections == rhs.detections;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::warehouse_sorting_msgs::ScanRequestResponse_<ContainerAllocator1> & lhs, const ::warehouse_sorting_msgs::ScanRequestResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace warehouse_sorting_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::warehouse_sorting_msgs::ScanRequestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::warehouse_sorting_msgs::ScanRequestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::warehouse_sorting_msgs::ScanRequestResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::warehouse_sorting_msgs::ScanRequestResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::warehouse_sorting_msgs::ScanRequestResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::warehouse_sorting_msgs::ScanRequestResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::warehouse_sorting_msgs::ScanRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cd4be7cf4af5e71c48052122ff3c1d88";
  }

  static const char* value(const ::warehouse_sorting_msgs::ScanRequestResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcd4be7cf4af5e71cULL;
  static const uint64_t static_value2 = 0x48052122ff3c1d88ULL;
};

template<class ContainerAllocator>
struct DataType< ::warehouse_sorting_msgs::ScanRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "warehouse_sorting_msgs/ScanRequestResponse";
  }

  static const char* value(const ::warehouse_sorting_msgs::ScanRequestResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::warehouse_sorting_msgs::ScanRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
"warehouse_sorting_msgs/DetectedCargoArray detections\n"
"\n"
"\n"
"================================================================================\n"
"MSG: warehouse_sorting_msgs/DetectedCargoArray\n"
"std_msgs/Header header\n"
"warehouse_sorting_msgs/Cargo[] objects\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: warehouse_sorting_msgs/Cargo\n"
"string cargo_id\n"
"string cargo_type\n"
"geometry_msgs/Pose pose\n"
"geometry_msgs/Vector3 size\n"
"float32 volume\n"
"float32 confidence\n"
"int32 bbox_x\n"
"int32 bbox_y\n"
"int32 bbox_width\n"
"int32 bbox_height\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::warehouse_sorting_msgs::ScanRequestResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::warehouse_sorting_msgs::ScanRequestResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
      stream.next(m.detections);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ScanRequestResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::warehouse_sorting_msgs::ScanRequestResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::warehouse_sorting_msgs::ScanRequestResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "detections: ";
    Printer< ::warehouse_sorting_msgs::DetectedCargoArray_<ContainerAllocator> >::stream(s, indent + "  ", v.detections);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAREHOUSE_SORTING_MSGS_MESSAGE_SCANREQUESTRESPONSE_H
