// Generated by gencpp from file warehouse_sorting_msgs/ScanRequestRequest.msg
// DO NOT EDIT!


#ifndef WAREHOUSE_SORTING_MSGS_MESSAGE_SCANREQUESTREQUEST_H
#define WAREHOUSE_SORTING_MSGS_MESSAGE_SCANREQUESTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace warehouse_sorting_msgs
{
template <class ContainerAllocator>
struct ScanRequestRequest_
{
  typedef ScanRequestRequest_<ContainerAllocator> Type;

  ScanRequestRequest_()
    : force(false)  {
    }
  ScanRequestRequest_(const ContainerAllocator& _alloc)
    : force(false)  {
  (void)_alloc;
    }



   typedef uint8_t _force_type;
  _force_type force;





  typedef boost::shared_ptr< ::warehouse_sorting_msgs::ScanRequestRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::warehouse_sorting_msgs::ScanRequestRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ScanRequestRequest_

typedef ::warehouse_sorting_msgs::ScanRequestRequest_<std::allocator<void> > ScanRequestRequest;

typedef boost::shared_ptr< ::warehouse_sorting_msgs::ScanRequestRequest > ScanRequestRequestPtr;
typedef boost::shared_ptr< ::warehouse_sorting_msgs::ScanRequestRequest const> ScanRequestRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::warehouse_sorting_msgs::ScanRequestRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::warehouse_sorting_msgs::ScanRequestRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::warehouse_sorting_msgs::ScanRequestRequest_<ContainerAllocator1> & lhs, const ::warehouse_sorting_msgs::ScanRequestRequest_<ContainerAllocator2> & rhs)
{
  return lhs.force == rhs.force;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::warehouse_sorting_msgs::ScanRequestRequest_<ContainerAllocator1> & lhs, const ::warehouse_sorting_msgs::ScanRequestRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace warehouse_sorting_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::warehouse_sorting_msgs::ScanRequestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::warehouse_sorting_msgs::ScanRequestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::warehouse_sorting_msgs::ScanRequestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::warehouse_sorting_msgs::ScanRequestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::warehouse_sorting_msgs::ScanRequestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::warehouse_sorting_msgs::ScanRequestRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::warehouse_sorting_msgs::ScanRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6fd3f14734166c254bff9db47985b674";
  }

  static const char* value(const ::warehouse_sorting_msgs::ScanRequestRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6fd3f14734166c25ULL;
  static const uint64_t static_value2 = 0x4bff9db47985b674ULL;
};

template<class ContainerAllocator>
struct DataType< ::warehouse_sorting_msgs::ScanRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "warehouse_sorting_msgs/ScanRequestRequest";
  }

  static const char* value(const ::warehouse_sorting_msgs::ScanRequestRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::warehouse_sorting_msgs::ScanRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool force\n"
;
  }

  static const char* value(const ::warehouse_sorting_msgs::ScanRequestRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::warehouse_sorting_msgs::ScanRequestRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.force);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ScanRequestRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::warehouse_sorting_msgs::ScanRequestRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::warehouse_sorting_msgs::ScanRequestRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "force: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.force);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAREHOUSE_SORTING_MSGS_MESSAGE_SCANREQUESTREQUEST_H
