// Generated by gencpp from file warehouse_sorting_msgs/TaskStatus.msg
// DO NOT EDIT!


#ifndef WAREHOUSE_SORTING_MSGS_MESSAGE_TASKSTATUS_H
#define WAREHOUSE_SORTING_MSGS_MESSAGE_TASKSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace warehouse_sorting_msgs
{
template <class ContainerAllocator>
struct TaskStatus_
{
  typedef TaskStatus_<ContainerAllocator> Type;

  TaskStatus_()
    : header()
    , task_id()
    , status()
    , total_items(0)
    , completed_items(0)
    , failed_items(0)
    , sorted_natural(0)
    , sorted_colored(0)
    , progress(0.0)
    , queue_size(0)
    , current_step()
    , last_error()  {
    }
  TaskStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , task_id(_alloc)
    , status(_alloc)
    , total_items(0)
    , completed_items(0)
    , failed_items(0)
    , sorted_natural(0)
    , sorted_colored(0)
    , progress(0.0)
    , queue_size(0)
    , current_step(_alloc)
    , last_error(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _task_id_type;
  _task_id_type task_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _status_type;
  _status_type status;

   typedef uint32_t _total_items_type;
  _total_items_type total_items;

   typedef uint32_t _completed_items_type;
  _completed_items_type completed_items;

   typedef uint32_t _failed_items_type;
  _failed_items_type failed_items;

   typedef uint32_t _sorted_natural_type;
  _sorted_natural_type sorted_natural;

   typedef uint32_t _sorted_colored_type;
  _sorted_colored_type sorted_colored;

   typedef float _progress_type;
  _progress_type progress;

   typedef uint32_t _queue_size_type;
  _queue_size_type queue_size;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _current_step_type;
  _current_step_type current_step;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _last_error_type;
  _last_error_type last_error;





  typedef boost::shared_ptr< ::warehouse_sorting_msgs::TaskStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::warehouse_sorting_msgs::TaskStatus_<ContainerAllocator> const> ConstPtr;

}; // struct TaskStatus_

typedef ::warehouse_sorting_msgs::TaskStatus_<std::allocator<void> > TaskStatus;

typedef boost::shared_ptr< ::warehouse_sorting_msgs::TaskStatus > TaskStatusPtr;
typedef boost::shared_ptr< ::warehouse_sorting_msgs::TaskStatus const> TaskStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::warehouse_sorting_msgs::TaskStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::warehouse_sorting_msgs::TaskStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::warehouse_sorting_msgs::TaskStatus_<ContainerAllocator1> & lhs, const ::warehouse_sorting_msgs::TaskStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.task_id == rhs.task_id &&
    lhs.status == rhs.status &&
    lhs.total_items == rhs.total_items &&
    lhs.completed_items == rhs.completed_items &&
    lhs.failed_items == rhs.failed_items &&
    lhs.sorted_natural == rhs.sorted_natural &&
    lhs.sorted_colored == rhs.sorted_colored &&
    lhs.progress == rhs.progress &&
    lhs.queue_size == rhs.queue_size &&
    lhs.current_step == rhs.current_step &&
    lhs.last_error == rhs.last_error;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::warehouse_sorting_msgs::TaskStatus_<ContainerAllocator1> & lhs, const ::warehouse_sorting_msgs::TaskStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace warehouse_sorting_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::warehouse_sorting_msgs::TaskStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::warehouse_sorting_msgs::TaskStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::warehouse_sorting_msgs::TaskStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::warehouse_sorting_msgs::TaskStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::warehouse_sorting_msgs::TaskStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::warehouse_sorting_msgs::TaskStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::warehouse_sorting_msgs::TaskStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b784d483d6404417f2b1da231522b939";
  }

  static const char* value(const ::warehouse_sorting_msgs::TaskStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb784d483d6404417ULL;
  static const uint64_t static_value2 = 0xf2b1da231522b939ULL;
};

template<class ContainerAllocator>
struct DataType< ::warehouse_sorting_msgs::TaskStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "warehouse_sorting_msgs/TaskStatus";
  }

  static const char* value(const ::warehouse_sorting_msgs::TaskStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::warehouse_sorting_msgs::TaskStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"string task_id\n"
"string status\n"
"uint32 total_items\n"
"uint32 completed_items\n"
"uint32 failed_items\n"
"uint32 sorted_natural\n"
"uint32 sorted_colored\n"
"float32 progress\n"
"uint32 queue_size\n"
"string current_step\n"
"string last_error\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::warehouse_sorting_msgs::TaskStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::warehouse_sorting_msgs::TaskStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.task_id);
      stream.next(m.status);
      stream.next(m.total_items);
      stream.next(m.completed_items);
      stream.next(m.failed_items);
      stream.next(m.sorted_natural);
      stream.next(m.sorted_colored);
      stream.next(m.progress);
      stream.next(m.queue_size);
      stream.next(m.current_step);
      stream.next(m.last_error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TaskStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::warehouse_sorting_msgs::TaskStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::warehouse_sorting_msgs::TaskStatus_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "task_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.task_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.status);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "total_items: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.total_items);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "completed_items: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.completed_items);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "failed_items: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.failed_items);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "sorted_natural: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.sorted_natural);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "sorted_colored: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.sorted_colored);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "progress: ";
    Printer<float>::stream(s, indent + "  ", v.progress);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "queue_size: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.queue_size);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "current_step: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.current_step);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "last_error: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.last_error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAREHOUSE_SORTING_MSGS_MESSAGE_TASKSTATUS_H
