// Generated by gencpp from file mapping/StartRequest.msg
// DO NOT EDIT!


#ifndef MAPPING_MESSAGE_STARTREQUEST_H
#define MAPPING_MESSAGE_STARTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mapping
{
template <class ContainerAllocator>
struct StartRequest_
{
  typedef StartRequest_<ContainerAllocator> Type;

  StartRequest_()
    : sim(false)
    , width(0.0)
    , height(0.0)  {
    }
  StartRequest_(const ContainerAllocator& _alloc)
    : sim(false)
    , width(0.0)
    , height(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _sim_type;
  _sim_type sim;

   typedef double _width_type;
  _width_type width;

   typedef double _height_type;
  _height_type height;





  typedef boost::shared_ptr< ::mapping::StartRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mapping::StartRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StartRequest_

typedef ::mapping::StartRequest_<std::allocator<void> > StartRequest;

typedef boost::shared_ptr< ::mapping::StartRequest > StartRequestPtr;
typedef boost::shared_ptr< ::mapping::StartRequest const> StartRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mapping::StartRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mapping::StartRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mapping::StartRequest_<ContainerAllocator1> & lhs, const ::mapping::StartRequest_<ContainerAllocator2> & rhs)
{
  return lhs.sim == rhs.sim &&
    lhs.width == rhs.width &&
    lhs.height == rhs.height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mapping::StartRequest_<ContainerAllocator1> & lhs, const ::mapping::StartRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mapping

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mapping::StartRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mapping::StartRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mapping::StartRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mapping::StartRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mapping::StartRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mapping::StartRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mapping::StartRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a70deabcef06834bdb6f0f2b35da8450";
  }

  static const char* value(const ::mapping::StartRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa70deabcef06834bULL;
  static const uint64_t static_value2 = 0xdb6f0f2b35da8450ULL;
};

template<class ContainerAllocator>
struct DataType< ::mapping::StartRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mapping/StartRequest";
  }

  static const char* value(const ::mapping::StartRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mapping::StartRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool sim # 明确是在仿真环境内还是在实际场景中\n"
"float64 width\n"
"float64 height\n"
;
  }

  static const char* value(const ::mapping::StartRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mapping::StartRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sim);
      stream.next(m.width);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mapping::StartRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mapping::StartRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "sim: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sim);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "width: ";
    Printer<double>::stream(s, indent + "  ", v.width);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "height: ";
    Printer<double>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAPPING_MESSAGE_STARTREQUEST_H
