// Generated by gencpp from file mapping/Start.msg
// DO NOT EDIT!


#ifndef MAPPING_MESSAGE_START_H
#define MAPPING_MESSAGE_START_H

#include <ros/service_traits.h>


#include <mapping/StartRequest.h>
#include <mapping/StartResponse.h>


namespace mapping
{

struct Start
{

typedef StartRequest Request;
typedef StartResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Start
} // namespace mapping


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mapping::Start > {
  static const char* value()
  {
    return "4dca6bc64797f691acd5d21876b3c9f4";
  }

  static const char* value(const ::mapping::Start&) { return value(); }
};

template<>
struct DataType< ::mapping::Start > {
  static const char* value()
  {
    return "mapping/Start";
  }

  static const char* value(const ::mapping::Start&) { return value(); }
};


// service_traits::MD5Sum< ::mapping::StartRequest> should match
// service_traits::MD5Sum< ::mapping::Start >
template<>
struct MD5Sum< ::mapping::StartRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mapping::Start >::value();
  }
  static const char* value(const ::mapping::StartRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mapping::StartRequest> should match
// service_traits::DataType< ::mapping::Start >
template<>
struct DataType< ::mapping::StartRequest>
{
  static const char* value()
  {
    return DataType< ::mapping::Start >::value();
  }
  static const char* value(const ::mapping::StartRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mapping::StartResponse> should match
// service_traits::MD5Sum< ::mapping::Start >
template<>
struct MD5Sum< ::mapping::StartResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mapping::Start >::value();
  }
  static const char* value(const ::mapping::StartResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mapping::StartResponse> should match
// service_traits::DataType< ::mapping::Start >
template<>
struct DataType< ::mapping::StartResponse>
{
  static const char* value()
  {
    return DataType< ::mapping::Start >::value();
  }
  static const char* value(const ::mapping::StartResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAPPING_MESSAGE_START_H
