// Generated by gencpp from file library_robot_interfaces/CameraFrameData.msg
// DO NOT EDIT!


#ifndef LIBRARY_ROBOT_INTERFACES_MESSAGE_CAMERAFRAMEDATA_H
#define LIBRARY_ROBOT_INTERFACES_MESSAGE_CAMERAFRAMEDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace library_robot_interfaces
{
template <class ContainerAllocator>
struct CameraFrameData_
{
  typedef CameraFrameData_<ContainerAllocator> Type;

  CameraFrameData_()
    : header()
    , frame_id(0)
    , format()
    , width(0)
    , height(0)
    , data_base64()
    , data_size(0)  {
    }
  CameraFrameData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , frame_id(0)
    , format(_alloc)
    , width(0)
    , height(0)
    , data_base64(_alloc)
    , data_size(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _frame_id_type;
  _frame_id_type frame_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _format_type;
  _format_type format;

   typedef int32_t _width_type;
  _width_type width;

   typedef int32_t _height_type;
  _height_type height;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _data_base64_type;
  _data_base64_type data_base64;

   typedef int32_t _data_size_type;
  _data_size_type data_size;





  typedef boost::shared_ptr< ::library_robot_interfaces::CameraFrameData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::library_robot_interfaces::CameraFrameData_<ContainerAllocator> const> ConstPtr;

}; // struct CameraFrameData_

typedef ::library_robot_interfaces::CameraFrameData_<std::allocator<void> > CameraFrameData;

typedef boost::shared_ptr< ::library_robot_interfaces::CameraFrameData > CameraFrameDataPtr;
typedef boost::shared_ptr< ::library_robot_interfaces::CameraFrameData const> CameraFrameDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::library_robot_interfaces::CameraFrameData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::library_robot_interfaces::CameraFrameData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::library_robot_interfaces::CameraFrameData_<ContainerAllocator1> & lhs, const ::library_robot_interfaces::CameraFrameData_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.frame_id == rhs.frame_id &&
    lhs.format == rhs.format &&
    lhs.width == rhs.width &&
    lhs.height == rhs.height &&
    lhs.data_base64 == rhs.data_base64 &&
    lhs.data_size == rhs.data_size;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::library_robot_interfaces::CameraFrameData_<ContainerAllocator1> & lhs, const ::library_robot_interfaces::CameraFrameData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace library_robot_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::library_robot_interfaces::CameraFrameData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::library_robot_interfaces::CameraFrameData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::library_robot_interfaces::CameraFrameData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::library_robot_interfaces::CameraFrameData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::library_robot_interfaces::CameraFrameData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::library_robot_interfaces::CameraFrameData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::library_robot_interfaces::CameraFrameData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "21126ab408dfc26931ec388ac082dc56";
  }

  static const char* value(const ::library_robot_interfaces::CameraFrameData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x21126ab408dfc269ULL;
  static const uint64_t static_value2 = 0x31ec388ac082dc56ULL;
};

template<class ContainerAllocator>
struct DataType< ::library_robot_interfaces::CameraFrameData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "library_robot_interfaces/CameraFrameData";
  }

  static const char* value(const ::library_robot_interfaces::CameraFrameData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::library_robot_interfaces::CameraFrameData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"int32 frame_id\n"
"string format          # e.g., \"jpeg\", \"png\"\n"
"int32 width\n"
"int32 height\n"
"string data_base64     # Base64编码的图像数据\n"
"int32 data_size        # 原始数据大小（字节） \n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::library_robot_interfaces::CameraFrameData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::library_robot_interfaces::CameraFrameData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.frame_id);
      stream.next(m.format);
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.data_base64);
      stream.next(m.data_size);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CameraFrameData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::library_robot_interfaces::CameraFrameData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::library_robot_interfaces::CameraFrameData_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "frame_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.frame_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "format: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.format);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "width: ";
    Printer<int32_t>::stream(s, indent + "  ", v.width);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "height: ";
    Printer<int32_t>::stream(s, indent + "  ", v.height);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "data_base64: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.data_base64);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "data_size: ";
    Printer<int32_t>::stream(s, indent + "  ", v.data_size);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIBRARY_ROBOT_INTERFACES_MESSAGE_CAMERAFRAMEDATA_H
