// Generated by gencpp from file library_robot_interfaces/RobotStatusCompressed.msg
// DO NOT EDIT!


#ifndef LIBRARY_ROBOT_INTERFACES_MESSAGE_ROBOTSTATUSCOMPRESSED_H
#define LIBRARY_ROBOT_INTERFACES_MESSAGE_ROBOTSTATUSCOMPRESSED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace library_robot_interfaces
{
template <class ContainerAllocator>
struct RobotStatusCompressed_
{
  typedef RobotStatusCompressed_<ContainerAllocator> Type;

  RobotStatusCompressed_()
    : header()
    , pose_x(0.0)
    , pose_y(0.0)
    , pose_theta(0.0)
    , velocity_linear(0.0)
    , velocity_angular(0.0)
    , battery_percentage(0.0)
    , robot_state_str()
    , error_message()
    , is_emergency_stopped(false)
    , active_task_id_rails(0)
    , active_map(0)  {
    }
  RobotStatusCompressed_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pose_x(0.0)
    , pose_y(0.0)
    , pose_theta(0.0)
    , velocity_linear(0.0)
    , velocity_angular(0.0)
    , battery_percentage(0.0)
    , robot_state_str(_alloc)
    , error_message(_alloc)
    , is_emergency_stopped(false)
    , active_task_id_rails(0)
    , active_map(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _pose_x_type;
  _pose_x_type pose_x;

   typedef float _pose_y_type;
  _pose_y_type pose_y;

   typedef float _pose_theta_type;
  _pose_theta_type pose_theta;

   typedef float _velocity_linear_type;
  _velocity_linear_type velocity_linear;

   typedef float _velocity_angular_type;
  _velocity_angular_type velocity_angular;

   typedef float _battery_percentage_type;
  _battery_percentage_type battery_percentage;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _robot_state_str_type;
  _robot_state_str_type robot_state_str;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _error_message_type;
  _error_message_type error_message;

   typedef uint8_t _is_emergency_stopped_type;
  _is_emergency_stopped_type is_emergency_stopped;

   typedef int32_t _active_task_id_rails_type;
  _active_task_id_rails_type active_task_id_rails;

   typedef int32_t _active_map_type;
  _active_map_type active_map;





  typedef boost::shared_ptr< ::library_robot_interfaces::RobotStatusCompressed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::library_robot_interfaces::RobotStatusCompressed_<ContainerAllocator> const> ConstPtr;

}; // struct RobotStatusCompressed_

typedef ::library_robot_interfaces::RobotStatusCompressed_<std::allocator<void> > RobotStatusCompressed;

typedef boost::shared_ptr< ::library_robot_interfaces::RobotStatusCompressed > RobotStatusCompressedPtr;
typedef boost::shared_ptr< ::library_robot_interfaces::RobotStatusCompressed const> RobotStatusCompressedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::library_robot_interfaces::RobotStatusCompressed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::library_robot_interfaces::RobotStatusCompressed_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::library_robot_interfaces::RobotStatusCompressed_<ContainerAllocator1> & lhs, const ::library_robot_interfaces::RobotStatusCompressed_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.pose_x == rhs.pose_x &&
    lhs.pose_y == rhs.pose_y &&
    lhs.pose_theta == rhs.pose_theta &&
    lhs.velocity_linear == rhs.velocity_linear &&
    lhs.velocity_angular == rhs.velocity_angular &&
    lhs.battery_percentage == rhs.battery_percentage &&
    lhs.robot_state_str == rhs.robot_state_str &&
    lhs.error_message == rhs.error_message &&
    lhs.is_emergency_stopped == rhs.is_emergency_stopped &&
    lhs.active_task_id_rails == rhs.active_task_id_rails &&
    lhs.active_map == rhs.active_map;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::library_robot_interfaces::RobotStatusCompressed_<ContainerAllocator1> & lhs, const ::library_robot_interfaces::RobotStatusCompressed_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace library_robot_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::library_robot_interfaces::RobotStatusCompressed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::library_robot_interfaces::RobotStatusCompressed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::library_robot_interfaces::RobotStatusCompressed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::library_robot_interfaces::RobotStatusCompressed_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::library_robot_interfaces::RobotStatusCompressed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::library_robot_interfaces::RobotStatusCompressed_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::library_robot_interfaces::RobotStatusCompressed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6fbfcb9ff0fd4a4ddc6e1fcb05506c41";
  }

  static const char* value(const ::library_robot_interfaces::RobotStatusCompressed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6fbfcb9ff0fd4a4dULL;
  static const uint64_t static_value2 = 0xdc6e1fcb05506c41ULL;
};

template<class ContainerAllocator>
struct DataType< ::library_robot_interfaces::RobotStatusCompressed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "library_robot_interfaces/RobotStatusCompressed";
  }

  static const char* value(const ::library_robot_interfaces::RobotStatusCompressed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::library_robot_interfaces::RobotStatusCompressed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"float32 pose_x\n"
"float32 pose_y\n"
"float32 pose_theta\n"
"float32 velocity_linear\n"
"float32 velocity_angular\n"
"float32 battery_percentage  # 0.0 到 100.0\n"
"string robot_state_str      # TaskManager维护的机器人状态字符串, e.g., \"idle\", \"mapping\", \"error_localization_lost\"\n"
"string error_message        # 当前错误信息 (如果有)\n"
"bool is_emergency_stopped\n"
"int32 active_task_id_rails # 当前正在执行的Rails Task ID (0 如果没有)\n"
"int32 active_map      # ROS中当前加载的地图的ID (0 如果没有)\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::library_robot_interfaces::RobotStatusCompressed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::library_robot_interfaces::RobotStatusCompressed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pose_x);
      stream.next(m.pose_y);
      stream.next(m.pose_theta);
      stream.next(m.velocity_linear);
      stream.next(m.velocity_angular);
      stream.next(m.battery_percentage);
      stream.next(m.robot_state_str);
      stream.next(m.error_message);
      stream.next(m.is_emergency_stopped);
      stream.next(m.active_task_id_rails);
      stream.next(m.active_map);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotStatusCompressed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::library_robot_interfaces::RobotStatusCompressed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::library_robot_interfaces::RobotStatusCompressed_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pose_x: ";
    Printer<float>::stream(s, indent + "  ", v.pose_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pose_y: ";
    Printer<float>::stream(s, indent + "  ", v.pose_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pose_theta: ";
    Printer<float>::stream(s, indent + "  ", v.pose_theta);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "velocity_linear: ";
    Printer<float>::stream(s, indent + "  ", v.velocity_linear);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "velocity_angular: ";
    Printer<float>::stream(s, indent + "  ", v.velocity_angular);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "battery_percentage: ";
    Printer<float>::stream(s, indent + "  ", v.battery_percentage);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "robot_state_str: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.robot_state_str);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "error_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.error_message);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "is_emergency_stopped: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_emergency_stopped);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "active_task_id_rails: ";
    Printer<int32_t>::stream(s, indent + "  ", v.active_task_id_rails);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "active_map: ";
    Printer<int32_t>::stream(s, indent + "  ", v.active_map);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIBRARY_ROBOT_INTERFACES_MESSAGE_ROBOTSTATUSCOMPRESSED_H
