// Generated by gencpp from file library_robot_interfaces/TaskDirective.msg
// DO NOT EDIT!


#ifndef LIBRARY_ROBOT_INTERFACES_MESSAGE_TASKDIRECTIVE_H
#define LIBRARY_ROBOT_INTERFACES_MESSAGE_TASKDIRECTIVE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace library_robot_interfaces
{
template <class ContainerAllocator>
struct TaskDirective_
{
  typedef TaskDirective_<ContainerAllocator> Type;

  TaskDirective_()
    : header()
    , command_type()
    , task_id_rails()
    , task_type_rails()
    , task_priority(0)
    , parameters_json()  {
    }
  TaskDirective_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , command_type(_alloc)
    , task_id_rails(_alloc)
    , task_type_rails(_alloc)
    , task_priority(0)
    , parameters_json(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _command_type_type;
  _command_type_type command_type;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _task_id_rails_type;
  _task_id_rails_type task_id_rails;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _task_type_rails_type;
  _task_type_rails_type task_type_rails;

   typedef int32_t _task_priority_type;
  _task_priority_type task_priority;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _parameters_json_type;
  _parameters_json_type parameters_json;





  typedef boost::shared_ptr< ::library_robot_interfaces::TaskDirective_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::library_robot_interfaces::TaskDirective_<ContainerAllocator> const> ConstPtr;

}; // struct TaskDirective_

typedef ::library_robot_interfaces::TaskDirective_<std::allocator<void> > TaskDirective;

typedef boost::shared_ptr< ::library_robot_interfaces::TaskDirective > TaskDirectivePtr;
typedef boost::shared_ptr< ::library_robot_interfaces::TaskDirective const> TaskDirectiveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::library_robot_interfaces::TaskDirective_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::library_robot_interfaces::TaskDirective_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::library_robot_interfaces::TaskDirective_<ContainerAllocator1> & lhs, const ::library_robot_interfaces::TaskDirective_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.command_type == rhs.command_type &&
    lhs.task_id_rails == rhs.task_id_rails &&
    lhs.task_type_rails == rhs.task_type_rails &&
    lhs.task_priority == rhs.task_priority &&
    lhs.parameters_json == rhs.parameters_json;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::library_robot_interfaces::TaskDirective_<ContainerAllocator1> & lhs, const ::library_robot_interfaces::TaskDirective_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace library_robot_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::library_robot_interfaces::TaskDirective_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::library_robot_interfaces::TaskDirective_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::library_robot_interfaces::TaskDirective_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::library_robot_interfaces::TaskDirective_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::library_robot_interfaces::TaskDirective_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::library_robot_interfaces::TaskDirective_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::library_robot_interfaces::TaskDirective_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d22fcfa77d7cca35dedf9ea427a99e6a";
  }

  static const char* value(const ::library_robot_interfaces::TaskDirective_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd22fcfa77d7cca35ULL;
  static const uint64_t static_value2 = 0xdedf9ea427a99e6aULL;
};

template<class ContainerAllocator>
struct DataType< ::library_robot_interfaces::TaskDirective_<ContainerAllocator> >
{
  static const char* value()
  {
    return "library_robot_interfaces/TaskDirective";
  }

  static const char* value(const ::library_robot_interfaces::TaskDirective_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::library_robot_interfaces::TaskDirective_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"string command_type          # 例如: \"TASK_EXECUTE\", \"TASK_CANCEL\", \"MOVE\", \"EMERGENCY_STOP\"\n"
"string task_id_rails         # Rails Task ID (如果适用，对于即时命令可以为空或特定值)\n"
"string task_type_rails       # 例如: \"MAP_BUILD_AUTO\", \"LOAD_MAP\", 或对于即时命令，同command_type\n"
"int32 task_priority         # 任务优先级，0表示最低，10表示最高\n"
"string parameters_json       # JSON字符串，包含任务或命令所需的参数\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::library_robot_interfaces::TaskDirective_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::library_robot_interfaces::TaskDirective_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.command_type);
      stream.next(m.task_id_rails);
      stream.next(m.task_type_rails);
      stream.next(m.task_priority);
      stream.next(m.parameters_json);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TaskDirective_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::library_robot_interfaces::TaskDirective_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::library_robot_interfaces::TaskDirective_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "command_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.command_type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "task_id_rails: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.task_id_rails);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "task_type_rails: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.task_type_rails);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "task_priority: ";
    Printer<int32_t>::stream(s, indent + "  ", v.task_priority);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "parameters_json: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.parameters_json);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIBRARY_ROBOT_INTERFACES_MESSAGE_TASKDIRECTIVE_H
