// Generated by gencpp from file library_robot_interfaces/TaskFeedback.msg
// DO NOT EDIT!


#ifndef LIBRARY_ROBOT_INTERFACES_MESSAGE_TASKFEEDBACK_H
#define LIBRARY_ROBOT_INTERFACES_MESSAGE_TASKFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace library_robot_interfaces
{
template <class ContainerAllocator>
struct TaskFeedback_
{
  typedef TaskFeedback_<ContainerAllocator> Type;

  TaskFeedback_()
    : header()
    , feedback_action_rails()
    , feedback_payload_json()  {
    }
  TaskFeedback_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , feedback_action_rails(_alloc)
    , feedback_payload_json(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _feedback_action_rails_type;
  _feedback_action_rails_type feedback_action_rails;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _feedback_payload_json_type;
  _feedback_payload_json_type feedback_payload_json;





  typedef boost::shared_ptr< ::library_robot_interfaces::TaskFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::library_robot_interfaces::TaskFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct TaskFeedback_

typedef ::library_robot_interfaces::TaskFeedback_<std::allocator<void> > TaskFeedback;

typedef boost::shared_ptr< ::library_robot_interfaces::TaskFeedback > TaskFeedbackPtr;
typedef boost::shared_ptr< ::library_robot_interfaces::TaskFeedback const> TaskFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::library_robot_interfaces::TaskFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::library_robot_interfaces::TaskFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::library_robot_interfaces::TaskFeedback_<ContainerAllocator1> & lhs, const ::library_robot_interfaces::TaskFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.feedback_action_rails == rhs.feedback_action_rails &&
    lhs.feedback_payload_json == rhs.feedback_payload_json;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::library_robot_interfaces::TaskFeedback_<ContainerAllocator1> & lhs, const ::library_robot_interfaces::TaskFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace library_robot_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::library_robot_interfaces::TaskFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::library_robot_interfaces::TaskFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::library_robot_interfaces::TaskFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::library_robot_interfaces::TaskFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::library_robot_interfaces::TaskFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::library_robot_interfaces::TaskFeedback_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::library_robot_interfaces::TaskFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "701107acf61196810ba751bfea18045a";
  }

  static const char* value(const ::library_robot_interfaces::TaskFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x701107acf6119681ULL;
  static const uint64_t static_value2 = 0x0ba751bfea18045aULL;
};

template<class ContainerAllocator>
struct DataType< ::library_robot_interfaces::TaskFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "library_robot_interfaces/TaskFeedback";
  }

  static const char* value(const ::library_robot_interfaces::TaskFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::library_robot_interfaces::TaskFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"# string task_id_rails            # 此反馈相关的Rails Task ID (如果适用)\n"
"string feedback_action_rails    # 要在Rails RobotFeedbackChannel上调用的方法名\n"
"                                # 例如: \"update_task_progress\", \"report_map_preview\", \"report_task_completion\"\n"
"string feedback_payload_json    # JSON字符串，作为上述Rails Channel方法的payload\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::library_robot_interfaces::TaskFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::library_robot_interfaces::TaskFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.feedback_action_rails);
      stream.next(m.feedback_payload_json);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TaskFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::library_robot_interfaces::TaskFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::library_robot_interfaces::TaskFeedback_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "feedback_action_rails: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.feedback_action_rails);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "feedback_payload_json: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.feedback_payload_json);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIBRARY_ROBOT_INTERFACES_MESSAGE_TASKFEEDBACK_H
