# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from library_robot_interfaces/RobotStatusCompressed.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class RobotStatusCompressed(genpy.Message):
  _md5sum = "6fbfcb9ff0fd4a4ddc6e1fcb05506c41"
  _type = "library_robot_interfaces/RobotStatusCompressed"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
float32 pose_x
float32 pose_y
float32 pose_theta
float32 velocity_linear
float32 velocity_angular
float32 battery_percentage  # 0.0 到 100.0
string robot_state_str      # TaskManager维护的机器人状态字符串, e.g., "idle", "mapping", "error_localization_lost"
string error_message        # 当前错误信息 (如果有)
bool is_emergency_stopped
int32 active_task_id_rails # 当前正在执行的Rails Task ID (0 如果没有)
int32 active_map      # ROS中当前加载的地图的ID (0 如果没有)
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','pose_x','pose_y','pose_theta','velocity_linear','velocity_angular','battery_percentage','robot_state_str','error_message','is_emergency_stopped','active_task_id_rails','active_map']
  _slot_types = ['std_msgs/Header','float32','float32','float32','float32','float32','float32','string','string','bool','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,pose_x,pose_y,pose_theta,velocity_linear,velocity_angular,battery_percentage,robot_state_str,error_message,is_emergency_stopped,active_task_id_rails,active_map

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RobotStatusCompressed, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.pose_x is None:
        self.pose_x = 0.
      if self.pose_y is None:
        self.pose_y = 0.
      if self.pose_theta is None:
        self.pose_theta = 0.
      if self.velocity_linear is None:
        self.velocity_linear = 0.
      if self.velocity_angular is None:
        self.velocity_angular = 0.
      if self.battery_percentage is None:
        self.battery_percentage = 0.
      if self.robot_state_str is None:
        self.robot_state_str = ''
      if self.error_message is None:
        self.error_message = ''
      if self.is_emergency_stopped is None:
        self.is_emergency_stopped = False
      if self.active_task_id_rails is None:
        self.active_task_id_rails = 0
      if self.active_map is None:
        self.active_map = 0
    else:
      self.header = std_msgs.msg.Header()
      self.pose_x = 0.
      self.pose_y = 0.
      self.pose_theta = 0.
      self.velocity_linear = 0.
      self.velocity_angular = 0.
      self.battery_percentage = 0.
      self.robot_state_str = ''
      self.error_message = ''
      self.is_emergency_stopped = False
      self.active_task_id_rails = 0
      self.active_map = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_6f().pack(_x.pose_x, _x.pose_y, _x.pose_theta, _x.velocity_linear, _x.velocity_angular, _x.battery_percentage))
      _x = self.robot_state_str
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.error_message
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B2i().pack(_x.is_emergency_stopped, _x.active_task_id_rails, _x.active_map))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.pose_x, _x.pose_y, _x.pose_theta, _x.velocity_linear, _x.velocity_angular, _x.battery_percentage,) = _get_struct_6f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.robot_state_str = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.robot_state_str = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.error_message = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.error_message = str[start:end]
      _x = self
      start = end
      end += 9
      (_x.is_emergency_stopped, _x.active_task_id_rails, _x.active_map,) = _get_struct_B2i().unpack(str[start:end])
      self.is_emergency_stopped = bool(self.is_emergency_stopped)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_6f().pack(_x.pose_x, _x.pose_y, _x.pose_theta, _x.velocity_linear, _x.velocity_angular, _x.battery_percentage))
      _x = self.robot_state_str
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.error_message
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B2i().pack(_x.is_emergency_stopped, _x.active_task_id_rails, _x.active_map))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.pose_x, _x.pose_y, _x.pose_theta, _x.velocity_linear, _x.velocity_angular, _x.battery_percentage,) = _get_struct_6f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.robot_state_str = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.robot_state_str = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.error_message = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.error_message = str[start:end]
      _x = self
      start = end
      end += 9
      (_x.is_emergency_stopped, _x.active_task_id_rails, _x.active_map,) = _get_struct_B2i().unpack(str[start:end])
      self.is_emergency_stopped = bool(self.is_emergency_stopped)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_6f = None
def _get_struct_6f():
    global _struct_6f
    if _struct_6f is None:
        _struct_6f = struct.Struct("<6f")
    return _struct_6f
_struct_B2i = None
def _get_struct_B2i():
    global _struct_B2i
    if _struct_B2i is None:
        _struct_B2i = struct.Struct("<B2i")
    return _struct_B2i
