
(cl:in-package :asdf)

(defsystem "vizanti-srv"
  :depends-on (:roslisp-msg-protocol :roslisp-utils )
  :components ((:file "_package")
    (:file "GetNodeParameters" :depends-on ("_package_GetNodeParameters"))
    (:file "_package_GetNodeParameters" :depends-on ("_package"))
    (:file "ListExecutables" :depends-on ("_package_ListExecutables"))
    (:file "_package_ListExecutables" :depends-on ("_package"))
    (:file "ListPackages" :depends-on ("_package_ListPackages"))
    (:file "_package_ListPackages" :depends-on ("_package"))
    (:file "LoadMap" :depends-on ("_package_LoadMap"))
    (:file "_package_LoadMap" :depends-on ("_package"))
    (:file "ManageNode" :depends-on ("_package_ManageNode"))
    (:file "_package_ManageNode" :depends-on ("_package"))
    (:file "RecordRosbag" :depends-on ("_package_RecordRosbag"))
    (:file "_package_RecordRosbag" :depends-on ("_package"))
    (:file "SaveMap" :depends-on ("_package_SaveMap"))
    (:file "_package_SaveMap" :depends-on ("_package"))
  ))