# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from palletizing/PalletizingStats.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class PalletizingStats(genpy.Message):
  _md5sum = "92aa1e36e09f1e3fca1e85e1659ad3fe"
  _type = "palletizing/PalletizingStats"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint32 total_objects
uint32 success_count
uint32 fail_count
uint32 current_layer
uint32 hard_zone_layers
uint32 soft_zone_layers
float64 success_rate
float64 avg_cycle_time
float64 elapsed_time
string current_state
"""
  __slots__ = ['total_objects','success_count','fail_count','current_layer','hard_zone_layers','soft_zone_layers','success_rate','avg_cycle_time','elapsed_time','current_state']
  _slot_types = ['uint32','uint32','uint32','uint32','uint32','uint32','float64','float64','float64','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       total_objects,success_count,fail_count,current_layer,hard_zone_layers,soft_zone_layers,success_rate,avg_cycle_time,elapsed_time,current_state

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PalletizingStats, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.total_objects is None:
        self.total_objects = 0
      if self.success_count is None:
        self.success_count = 0
      if self.fail_count is None:
        self.fail_count = 0
      if self.current_layer is None:
        self.current_layer = 0
      if self.hard_zone_layers is None:
        self.hard_zone_layers = 0
      if self.soft_zone_layers is None:
        self.soft_zone_layers = 0
      if self.success_rate is None:
        self.success_rate = 0.
      if self.avg_cycle_time is None:
        self.avg_cycle_time = 0.
      if self.elapsed_time is None:
        self.elapsed_time = 0.
      if self.current_state is None:
        self.current_state = ''
    else:
      self.total_objects = 0
      self.success_count = 0
      self.fail_count = 0
      self.current_layer = 0
      self.hard_zone_layers = 0
      self.soft_zone_layers = 0
      self.success_rate = 0.
      self.avg_cycle_time = 0.
      self.elapsed_time = 0.
      self.current_state = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6I3d().pack(_x.total_objects, _x.success_count, _x.fail_count, _x.current_layer, _x.hard_zone_layers, _x.soft_zone_layers, _x.success_rate, _x.avg_cycle_time, _x.elapsed_time))
      _x = self.current_state
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.total_objects, _x.success_count, _x.fail_count, _x.current_layer, _x.hard_zone_layers, _x.soft_zone_layers, _x.success_rate, _x.avg_cycle_time, _x.elapsed_time,) = _get_struct_6I3d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.current_state = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.current_state = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6I3d().pack(_x.total_objects, _x.success_count, _x.fail_count, _x.current_layer, _x.hard_zone_layers, _x.soft_zone_layers, _x.success_rate, _x.avg_cycle_time, _x.elapsed_time))
      _x = self.current_state
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.total_objects, _x.success_count, _x.fail_count, _x.current_layer, _x.hard_zone_layers, _x.soft_zone_layers, _x.success_rate, _x.avg_cycle_time, _x.elapsed_time,) = _get_struct_6I3d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.current_state = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.current_state = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6I3d = None
def _get_struct_6I3d():
    global _struct_6I3d
    if _struct_6I3d is None:
        _struct_6I3d = struct.Struct("<6I3d")
    return _struct_6I3d
