(cl:defpackage palletizing-srv
  (:use )
  (:export
   "SYSTEMRESET"
   "<SYSTEMRESET-REQUEST>"
   "SYSTEMRESET-REQUEST"
   "<SYSTEMRESET-RESPONSE>"
   "SYSTEMRESET-RESPONSE"
   "TRIGGERDETECTION"
   "<TRIGGERDETECTION-REQUEST>"
   "TRIGGERDETECTION-REQUEST"
   "<TRIGGERDETECTION-RESPONSE>"
   "TRIGGERDETECTION-RESPONSE"
  ))

