(cl:defpackage palletizing-srv
  (:use )
  (:export
   "MARKZONE"
   "<MARKZONE-REQUEST>"
   "MARKZONE-REQUEST"
   "<MARKZONE-RESPONSE>"
   "MARKZONE-RESPONSE"
   "STARTTASK"
   "<STARTTASK-REQUEST>"
   "STARTTASK-REQUEST"
   "<STARTTASK-RESPONSE>"
   "STARTTASK-RESPONSE"
  ))

