; Auto-generated. Do not edit!


(cl:in-package navigation-msg)


;//! \htmlinclude NavigateFeedback.msg.html

(cl:defclass <NavigateFeedback> (roslisp-msg-protocol:ros-message)
  ((percentage
    :reader percentage
    :initarg :percentage
    :type cl:fixnum
    :initform 0)
   (cur_state
    :reader cur_state
    :initarg :cur_state
    :type cl:string
    :initform ""))
)

(cl:defclass NavigateFeedback (<NavigateFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <NavigateFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'NavigateFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name navigation-msg:<NavigateFeedback> is deprecated: use navigation-msg:NavigateFeedback instead.")))

(cl:ensure-generic-function 'percentage-val :lambda-list '(m))
(cl:defmethod percentage-val ((m <NavigateFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader navigation-msg:percentage-val is deprecated.  Use navigation-msg:percentage instead.")
  (percentage m))

(cl:ensure-generic-function 'cur_state-val :lambda-list '(m))
(cl:defmethod cur_state-val ((m <NavigateFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader navigation-msg:cur_state-val is deprecated.  Use navigation-msg:cur_state instead.")
  (cur_state m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <NavigateFeedback>) ostream)
  "Serializes a message object of type '<NavigateFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'percentage)) ostream)
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'cur_state))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'cur_state))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <NavigateFeedback>) istream)
  "Deserializes a message object of type '<NavigateFeedback>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'percentage)) (cl:read-byte istream))
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'cur_state) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'cur_state) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<NavigateFeedback>)))
  "Returns string type for a message object of type '<NavigateFeedback>"
  "navigation/NavigateFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'NavigateFeedback)))
  "Returns string type for a message object of type 'NavigateFeedback"
  "navigation/NavigateFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<NavigateFeedback>)))
  "Returns md5sum for a message object of type '<NavigateFeedback>"
  "e55f37833d45ecf45efa89550ac3c9d5")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'NavigateFeedback)))
  "Returns md5sum for a message object of type 'NavigateFeedback"
  "e55f37833d45ecf45efa89550ac3c9d5")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<NavigateFeedback>)))
  "Returns full string definition for message of type '<NavigateFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint8 percentage # 进度~%string cur_state # 'normal' 'barrier' 'planning'~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'NavigateFeedback)))
  "Returns full string definition for message of type 'NavigateFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint8 percentage # 进度~%string cur_state # 'normal' 'barrier' 'planning'~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <NavigateFeedback>))
  (cl:+ 0
     1
     4 (cl:length (cl:slot-value msg 'cur_state))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <NavigateFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'NavigateFeedback
    (cl:cons ':percentage (percentage msg))
    (cl:cons ':cur_state (cur_state msg))
))
