; Auto-generated. Do not edit!


(cl:in-package palletizing-msg)


;//! \htmlinclude GrabGoal.msg.html

(cl:defclass <GrabGoal> (roslisp-msg-protocol:ros-message)
  ((target_position
    :reader target_position
    :initarg :target_position
    :type geometry_msgs-msg:Point
    :initform (cl:make-instance 'geometry_msgs-msg:Point)))
)

(cl:defclass GrabGoal (<GrabGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GrabGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GrabGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name palletizing-msg:<GrabGoal> is deprecated: use palletizing-msg:GrabGoal instead.")))

(cl:ensure-generic-function 'target_position-val :lambda-list '(m))
(cl:defmethod target_position-val ((m <GrabGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader palletizing-msg:target_position-val is deprecated.  Use palletizing-msg:target_position instead.")
  (target_position m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GrabGoal>) ostream)
  "Serializes a message object of type '<GrabGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'target_position) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GrabGoal>) istream)
  "Deserializes a message object of type '<GrabGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'target_position) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GrabGoal>)))
  "Returns string type for a message object of type '<GrabGoal>"
  "palletizing/GrabGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GrabGoal)))
  "Returns string type for a message object of type 'GrabGoal"
  "palletizing/GrabGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GrabGoal>)))
  "Returns md5sum for a message object of type '<GrabGoal>"
  "f75376e65983f8c060d677c4184eba54")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GrabGoal)))
  "Returns md5sum for a message object of type 'GrabGoal"
  "f75376e65983f8c060d677c4184eba54")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GrabGoal>)))
  "Returns full string definition for message of type '<GrabGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# 抓取 Action：控制机械臂执行抓取动作~%# ─── Goal ───~%geometry_msgs/Point target_position~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GrabGoal)))
  "Returns full string definition for message of type 'GrabGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# 抓取 Action：控制机械臂执行抓取动作~%# ─── Goal ───~%geometry_msgs/Point target_position~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GrabGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'target_position))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GrabGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'GrabGoal
    (cl:cons ':target_position (target_position msg))
))
