; Auto-generated. Do not edit!


(cl:in-package palletizing-msg)


;//! \htmlinclude NavigateGoal.msg.html

(cl:defclass <NavigateGoal> (roslisp-msg-protocol:ros-message)
  ((target_name
    :reader target_name
    :initarg :target_name
    :type cl:string
    :initform "")
   (target_pose
    :reader target_pose
    :initarg :target_pose
    :type geometry_msgs-msg:Pose
    :initform (cl:make-instance 'geometry_msgs-msg:Pose)))
)

(cl:defclass NavigateGoal (<NavigateGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <NavigateGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'NavigateGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name palletizing-msg:<NavigateGoal> is deprecated: use palletizing-msg:NavigateGoal instead.")))

(cl:ensure-generic-function 'target_name-val :lambda-list '(m))
(cl:defmethod target_name-val ((m <NavigateGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader palletizing-msg:target_name-val is deprecated.  Use palletizing-msg:target_name instead.")
  (target_name m))

(cl:ensure-generic-function 'target_pose-val :lambda-list '(m))
(cl:defmethod target_pose-val ((m <NavigateGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader palletizing-msg:target_pose-val is deprecated.  Use palletizing-msg:target_pose instead.")
  (target_pose m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <NavigateGoal>) ostream)
  "Serializes a message object of type '<NavigateGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'target_name))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'target_name))
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'target_pose) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <NavigateGoal>) istream)
  "Deserializes a message object of type '<NavigateGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'target_name) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'target_name) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'target_pose) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<NavigateGoal>)))
  "Returns string type for a message object of type '<NavigateGoal>"
  "palletizing/NavigateGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'NavigateGoal)))
  "Returns string type for a message object of type 'NavigateGoal"
  "palletizing/NavigateGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<NavigateGoal>)))
  "Returns md5sum for a message object of type '<NavigateGoal>"
  "2c8141c8a1d68d5f316844c6369eeb38")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'NavigateGoal)))
  "Returns md5sum for a message object of type 'NavigateGoal"
  "2c8141c8a1d68d5f316844c6369eeb38")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<NavigateGoal>)))
  "Returns full string definition for message of type '<NavigateGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# 导航 Action：驱动底盘移动至指定目标点~%# ─── Goal ───~%string target_name~%geometry_msgs/Pose target_pose~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'NavigateGoal)))
  "Returns full string definition for message of type 'NavigateGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# 导航 Action：驱动底盘移动至指定目标点~%# ─── Goal ───~%string target_name~%geometry_msgs/Pose target_pose~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <NavigateGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'target_name))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'target_pose))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <NavigateGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'NavigateGoal
    (cl:cons ':target_name (target_name msg))
    (cl:cons ':target_pose (target_pose msg))
))
