; Auto-generated. Do not edit!


(cl:in-package palletizing-msg)


;//! \htmlinclude PalletizeGoal.msg.html

(cl:defclass <PalletizeGoal> (roslisp-msg-protocol:ros-message)
  ((layer
    :reader layer
    :initarg :layer
    :type cl:fixnum
    :initform 0)
   (place_position
    :reader place_position
    :initarg :place_position
    :type geometry_msgs-msg:Point
    :initform (cl:make-instance 'geometry_msgs-msg:Point)))
)

(cl:defclass PalletizeGoal (<PalletizeGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PalletizeGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PalletizeGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name palletizing-msg:<PalletizeGoal> is deprecated: use palletizing-msg:PalletizeGoal instead.")))

(cl:ensure-generic-function 'layer-val :lambda-list '(m))
(cl:defmethod layer-val ((m <PalletizeGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader palletizing-msg:layer-val is deprecated.  Use palletizing-msg:layer instead.")
  (layer m))

(cl:ensure-generic-function 'place_position-val :lambda-list '(m))
(cl:defmethod place_position-val ((m <PalletizeGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader palletizing-msg:place_position-val is deprecated.  Use palletizing-msg:place_position instead.")
  (place_position m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PalletizeGoal>) ostream)
  "Serializes a message object of type '<PalletizeGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'layer)) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'place_position) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PalletizeGoal>) istream)
  "Deserializes a message object of type '<PalletizeGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'layer)) (cl:read-byte istream))
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'place_position) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PalletizeGoal>)))
  "Returns string type for a message object of type '<PalletizeGoal>"
  "palletizing/PalletizeGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PalletizeGoal)))
  "Returns string type for a message object of type 'PalletizeGoal"
  "palletizing/PalletizeGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PalletizeGoal>)))
  "Returns md5sum for a message object of type '<PalletizeGoal>"
  "ab64145f46649d32273906cef7ee7209")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PalletizeGoal)))
  "Returns md5sum for a message object of type 'PalletizeGoal"
  "ab64145f46649d32273906cef7ee7209")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PalletizeGoal>)))
  "Returns full string definition for message of type '<PalletizeGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# 码垛 Action：将货物放置到目标位置（支持多层）~%# ─── Goal ───~%uint8 layer~%geometry_msgs/Point place_position~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PalletizeGoal)))
  "Returns full string definition for message of type 'PalletizeGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# 码垛 Action：将货物放置到目标位置（支持多层）~%# ─── Goal ───~%uint8 layer~%geometry_msgs/Point place_position~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PalletizeGoal>))
  (cl:+ 0
     1
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'place_position))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PalletizeGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'PalletizeGoal
    (cl:cons ':layer (layer msg))
    (cl:cons ':place_position (place_position msg))
))
