
(cl:in-package :asdf)

(defsystem "palletizing-msg"
  :depends-on (:roslisp-msg-protocol :roslisp-utils :actionlib_msgs-msg
               :geometry_msgs-msg
               :std_msgs-msg
)
  :components ((:file "_package")
    (:file "GrabAction" :depends-on ("_package_GrabAction"))
    (:file "_package_GrabAction" :depends-on ("_package"))
    (:file "GrabActionFeedback" :depends-on ("_package_GrabActionFeedback"))
    (:file "_package_GrabActionFeedback" :depends-on ("_package"))
    (:file "GrabActionGoal" :depends-on ("_package_GrabActionGoal"))
    (:file "_package_GrabActionGoal" :depends-on ("_package"))
    (:file "GrabActionResult" :depends-on ("_package_GrabActionResult"))
    (:file "_package_GrabActionResult" :depends-on ("_package"))
    (:file "GrabFeedback" :depends-on ("_package_GrabFeedback"))
    (:file "_package_GrabFeedback" :depends-on ("_package"))
    (:file "GrabGoal" :depends-on ("_package_GrabGoal"))
    (:file "_package_GrabGoal" :depends-on ("_package"))
    (:file "GrabResult" :depends-on ("_package_GrabResult"))
    (:file "_package_GrabResult" :depends-on ("_package"))
    (:file "NavigateAction" :depends-on ("_package_NavigateAction"))
    (:file "_package_NavigateAction" :depends-on ("_package"))
    (:file "NavigateActionFeedback" :depends-on ("_package_NavigateActionFeedback"))
    (:file "_package_NavigateActionFeedback" :depends-on ("_package"))
    (:file "NavigateActionGoal" :depends-on ("_package_NavigateActionGoal"))
    (:file "_package_NavigateActionGoal" :depends-on ("_package"))
    (:file "NavigateActionResult" :depends-on ("_package_NavigateActionResult"))
    (:file "_package_NavigateActionResult" :depends-on ("_package"))
    (:file "NavigateFeedback" :depends-on ("_package_NavigateFeedback"))
    (:file "_package_NavigateFeedback" :depends-on ("_package"))
    (:file "NavigateGoal" :depends-on ("_package_NavigateGoal"))
    (:file "_package_NavigateGoal" :depends-on ("_package"))
    (:file "NavigateResult" :depends-on ("_package_NavigateResult"))
    (:file "_package_NavigateResult" :depends-on ("_package"))
    (:file "PalletizeAction" :depends-on ("_package_PalletizeAction"))
    (:file "_package_PalletizeAction" :depends-on ("_package"))
    (:file "PalletizeActionFeedback" :depends-on ("_package_PalletizeActionFeedback"))
    (:file "_package_PalletizeActionFeedback" :depends-on ("_package"))
    (:file "PalletizeActionGoal" :depends-on ("_package_PalletizeActionGoal"))
    (:file "_package_PalletizeActionGoal" :depends-on ("_package"))
    (:file "PalletizeActionResult" :depends-on ("_package_PalletizeActionResult"))
    (:file "_package_PalletizeActionResult" :depends-on ("_package"))
    (:file "PalletizeFeedback" :depends-on ("_package_PalletizeFeedback"))
    (:file "_package_PalletizeFeedback" :depends-on ("_package"))
    (:file "PalletizeGoal" :depends-on ("_package_PalletizeGoal"))
    (:file "_package_PalletizeGoal" :depends-on ("_package"))
    (:file "PalletizeResult" :depends-on ("_package_PalletizeResult"))
    (:file "_package_PalletizeResult" :depends-on ("_package"))
  ))