// Generated by gencpp from file navigation/Goal.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MESSAGE_GOAL_H
#define NAVIGATION_MESSAGE_GOAL_H

#include <ros/service_traits.h>


#include <navigation/GoalRequest.h>
#include <navigation/GoalResponse.h>


namespace navigation
{

struct Goal
{

typedef GoalRequest Request;
typedef GoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Goal
} // namespace navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::navigation::Goal > {
  static const char* value()
  {
    return "9ef9882ea5e1807374359bbbddadd9f1";
  }

  static const char* value(const ::navigation::Goal&) { return value(); }
};

template<>
struct DataType< ::navigation::Goal > {
  static const char* value()
  {
    return "navigation/Goal";
  }

  static const char* value(const ::navigation::Goal&) { return value(); }
};


// service_traits::MD5Sum< ::navigation::GoalRequest> should match
// service_traits::MD5Sum< ::navigation::Goal >
template<>
struct MD5Sum< ::navigation::GoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::navigation::Goal >::value();
  }
  static const char* value(const ::navigation::GoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation::GoalRequest> should match
// service_traits::DataType< ::navigation::Goal >
template<>
struct DataType< ::navigation::GoalRequest>
{
  static const char* value()
  {
    return DataType< ::navigation::Goal >::value();
  }
  static const char* value(const ::navigation::GoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::navigation::GoalResponse> should match
// service_traits::MD5Sum< ::navigation::Goal >
template<>
struct MD5Sum< ::navigation::GoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::navigation::Goal >::value();
  }
  static const char* value(const ::navigation::GoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation::GoalResponse> should match
// service_traits::DataType< ::navigation::Goal >
template<>
struct DataType< ::navigation::GoalResponse>
{
  static const char* value()
  {
    return DataType< ::navigation::Goal >::value();
  }
  static const char* value(const ::navigation::GoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAVIGATION_MESSAGE_GOAL_H
