// Generated by gencpp from file navigation/GoalRequest.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MESSAGE_GOALREQUEST_H
#define NAVIGATION_MESSAGE_GOALREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace navigation
{
template <class ContainerAllocator>
struct GoalRequest_
{
  typedef GoalRequest_<ContainerAllocator> Type;

  GoalRequest_()
    : px(0.0)
    , py(0.0)
    , oz(0.0)  {
    }
  GoalRequest_(const ContainerAllocator& _alloc)
    : px(0.0)
    , py(0.0)
    , oz(0.0)  {
  (void)_alloc;
    }



   typedef double _px_type;
  _px_type px;

   typedef double _py_type;
  _py_type py;

   typedef double _oz_type;
  _oz_type oz;





  typedef boost::shared_ptr< ::navigation::GoalRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation::GoalRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GoalRequest_

typedef ::navigation::GoalRequest_<std::allocator<void> > GoalRequest;

typedef boost::shared_ptr< ::navigation::GoalRequest > GoalRequestPtr;
typedef boost::shared_ptr< ::navigation::GoalRequest const> GoalRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation::GoalRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation::GoalRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::navigation::GoalRequest_<ContainerAllocator1> & lhs, const ::navigation::GoalRequest_<ContainerAllocator2> & rhs)
{
  return lhs.px == rhs.px &&
    lhs.py == rhs.py &&
    lhs.oz == rhs.oz;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::navigation::GoalRequest_<ContainerAllocator1> & lhs, const ::navigation::GoalRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::navigation::GoalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::GoalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation::GoalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation::GoalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::GoalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::GoalRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation::GoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4386b9607ec4c74ab28e0cffd7898375";
  }

  static const char* value(const ::navigation::GoalRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4386b9607ec4c74aULL;
  static const uint64_t static_value2 = 0xb28e0cffd7898375ULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation::GoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation/GoalRequest";
  }

  static const char* value(const ::navigation::GoalRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation::GoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 px\n"
"float64 py\n"
"float64 oz\n"
;
  }

  static const char* value(const ::navigation::GoalRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation::GoalRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.px);
      stream.next(m.py);
      stream.next(m.oz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoalRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation::GoalRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigation::GoalRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "px: ";
    Printer<double>::stream(s, indent + "  ", v.px);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "py: ";
    Printer<double>::stream(s, indent + "  ", v.py);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "oz: ";
    Printer<double>::stream(s, indent + "  ", v.oz);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_MESSAGE_GOALREQUEST_H
