// Generated by gencpp from file navigation/Halt.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MESSAGE_HALT_H
#define NAVIGATION_MESSAGE_HALT_H

#include <ros/service_traits.h>


#include <navigation/HaltRequest.h>
#include <navigation/HaltResponse.h>


namespace navigation
{

struct Halt
{

typedef HaltRequest Request;
typedef HaltResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Halt
} // namespace navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::navigation::Halt > {
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::navigation::Halt&) { return value(); }
};

template<>
struct DataType< ::navigation::Halt > {
  static const char* value()
  {
    return "navigation/Halt";
  }

  static const char* value(const ::navigation::Halt&) { return value(); }
};


// service_traits::MD5Sum< ::navigation::HaltRequest> should match
// service_traits::MD5Sum< ::navigation::Halt >
template<>
struct MD5Sum< ::navigation::HaltRequest>
{
  static const char* value()
  {
    return MD5Sum< ::navigation::Halt >::value();
  }
  static const char* value(const ::navigation::HaltRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation::HaltRequest> should match
// service_traits::DataType< ::navigation::Halt >
template<>
struct DataType< ::navigation::HaltRequest>
{
  static const char* value()
  {
    return DataType< ::navigation::Halt >::value();
  }
  static const char* value(const ::navigation::HaltRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::navigation::HaltResponse> should match
// service_traits::MD5Sum< ::navigation::Halt >
template<>
struct MD5Sum< ::navigation::HaltResponse>
{
  static const char* value()
  {
    return MD5Sum< ::navigation::Halt >::value();
  }
  static const char* value(const ::navigation::HaltResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation::HaltResponse> should match
// service_traits::DataType< ::navigation::Halt >
template<>
struct DataType< ::navigation::HaltResponse>
{
  static const char* value()
  {
    return DataType< ::navigation::Halt >::value();
  }
  static const char* value(const ::navigation::HaltResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAVIGATION_MESSAGE_HALT_H
