// Generated by gencpp from file navigation/StartRequest.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MESSAGE_STARTREQUEST_H
#define NAVIGATION_MESSAGE_STARTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace navigation
{
template <class ContainerAllocator>
struct StartRequest_
{
  typedef StartRequest_<ContainerAllocator> Type;

  StartRequest_()
    : sim(false)
    , map(false)
    , path()
    , name()  {
    }
  StartRequest_(const ContainerAllocator& _alloc)
    : sim(false)
    , map(false)
    , path(_alloc)
    , name(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _sim_type;
  _sim_type sim;

   typedef uint8_t _map_type;
  _map_type map;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _path_type;
  _path_type path;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::navigation::StartRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation::StartRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StartRequest_

typedef ::navigation::StartRequest_<std::allocator<void> > StartRequest;

typedef boost::shared_ptr< ::navigation::StartRequest > StartRequestPtr;
typedef boost::shared_ptr< ::navigation::StartRequest const> StartRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation::StartRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation::StartRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::navigation::StartRequest_<ContainerAllocator1> & lhs, const ::navigation::StartRequest_<ContainerAllocator2> & rhs)
{
  return lhs.sim == rhs.sim &&
    lhs.map == rhs.map &&
    lhs.path == rhs.path &&
    lhs.name == rhs.name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::navigation::StartRequest_<ContainerAllocator1> & lhs, const ::navigation::StartRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::navigation::StartRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::StartRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation::StartRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation::StartRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::StartRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::StartRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation::StartRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4260860a7f34559bba8b67f510793bf7";
  }

  static const char* value(const ::navigation::StartRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4260860a7f34559bULL;
  static const uint64_t static_value2 = 0xba8b67f510793bf7ULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation::StartRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation/StartRequest";
  }

  static const char* value(const ::navigation::StartRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation::StartRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool sim\n"
"bool map\n"
"string path # relative path under /media/mitchell/Data/Projects/software_engineering/ros_end/src/mapping/maps/\n"
"string name # name of map\n"
;
  }

  static const char* value(const ::navigation::StartRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation::StartRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sim);
      stream.next(m.map);
      stream.next(m.path);
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation::StartRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigation::StartRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "sim: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sim);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "map: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.map);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.path);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_MESSAGE_STARTREQUEST_H
