// Generated by gencpp from file palletizing/GrabFeedback.msg
// DO NOT EDIT!


#ifndef PALLETIZING_MESSAGE_GRABFEEDBACK_H
#define PALLETIZING_MESSAGE_GRABFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace palletizing
{
template <class ContainerAllocator>
struct GrabFeedback_
{
  typedef GrabFeedback_<ContainerAllocator> Type;

  GrabFeedback_()
    : phase()  {
    }
  GrabFeedback_(const ContainerAllocator& _alloc)
    : phase(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _phase_type;
  _phase_type phase;





  typedef boost::shared_ptr< ::palletizing::GrabFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::palletizing::GrabFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct GrabFeedback_

typedef ::palletizing::GrabFeedback_<std::allocator<void> > GrabFeedback;

typedef boost::shared_ptr< ::palletizing::GrabFeedback > GrabFeedbackPtr;
typedef boost::shared_ptr< ::palletizing::GrabFeedback const> GrabFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::palletizing::GrabFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::palletizing::GrabFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::palletizing::GrabFeedback_<ContainerAllocator1> & lhs, const ::palletizing::GrabFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.phase == rhs.phase;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::palletizing::GrabFeedback_<ContainerAllocator1> & lhs, const ::palletizing::GrabFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace palletizing

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::palletizing::GrabFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::palletizing::GrabFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::palletizing::GrabFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::palletizing::GrabFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::palletizing::GrabFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::palletizing::GrabFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::palletizing::GrabFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6d2d7be4891f7e41e801034b05c9586c";
  }

  static const char* value(const ::palletizing::GrabFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6d2d7be4891f7e41ULL;
  static const uint64_t static_value2 = 0xe801034b05c9586cULL;
};

template<class ContainerAllocator>
struct DataType< ::palletizing::GrabFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "palletizing/GrabFeedback";
  }

  static const char* value(const ::palletizing::GrabFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::palletizing::GrabFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# ─── Feedback ───\n"
"string phase\n"
"\n"
;
  }

  static const char* value(const ::palletizing::GrabFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::palletizing::GrabFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.phase);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GrabFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::palletizing::GrabFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::palletizing::GrabFeedback_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "phase: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.phase);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PALLETIZING_MESSAGE_GRABFEEDBACK_H
