// Generated by gencpp from file palletizing/MarkZoneResponse.msg
// DO NOT EDIT!


#ifndef PALLETIZING_MESSAGE_MARKZONERESPONSE_H
#define PALLETIZING_MESSAGE_MARKZONERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace palletizing
{
template <class ContainerAllocator>
struct MarkZoneResponse_
{
  typedef MarkZoneResponse_<ContainerAllocator> Type;

  MarkZoneResponse_()
    : success(false)  {
    }
  MarkZoneResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::palletizing::MarkZoneResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::palletizing::MarkZoneResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MarkZoneResponse_

typedef ::palletizing::MarkZoneResponse_<std::allocator<void> > MarkZoneResponse;

typedef boost::shared_ptr< ::palletizing::MarkZoneResponse > MarkZoneResponsePtr;
typedef boost::shared_ptr< ::palletizing::MarkZoneResponse const> MarkZoneResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::palletizing::MarkZoneResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::palletizing::MarkZoneResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::palletizing::MarkZoneResponse_<ContainerAllocator1> & lhs, const ::palletizing::MarkZoneResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::palletizing::MarkZoneResponse_<ContainerAllocator1> & lhs, const ::palletizing::MarkZoneResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace palletizing

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::palletizing::MarkZoneResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::palletizing::MarkZoneResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::palletizing::MarkZoneResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::palletizing::MarkZoneResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::palletizing::MarkZoneResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::palletizing::MarkZoneResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::palletizing::MarkZoneResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::palletizing::MarkZoneResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::palletizing::MarkZoneResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "palletizing/MarkZoneResponse";
  }

  static const char* value(const ::palletizing::MarkZoneResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::palletizing::MarkZoneResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::palletizing::MarkZoneResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::palletizing::MarkZoneResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MarkZoneResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::palletizing::MarkZoneResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::palletizing::MarkZoneResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PALLETIZING_MESSAGE_MARKZONERESPONSE_H
