// Generated by gencpp from file palletizing/MarkZone.msg
// DO NOT EDIT!


#ifndef PALLETIZING_MESSAGE_MARKZONE_H
#define PALLETIZING_MESSAGE_MARKZONE_H

#include <ros/service_traits.h>


#include <palletizing/MarkZoneRequest.h>
#include <palletizing/MarkZoneResponse.h>


namespace palletizing
{

struct MarkZone
{

typedef MarkZoneRequest Request;
typedef MarkZoneResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MarkZone
} // namespace palletizing


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::palletizing::MarkZone > {
  static const char* value()
  {
    return "4045fd5b1bf547873a43552f46cf555f";
  }

  static const char* value(const ::palletizing::MarkZone&) { return value(); }
};

template<>
struct DataType< ::palletizing::MarkZone > {
  static const char* value()
  {
    return "palletizing/MarkZone";
  }

  static const char* value(const ::palletizing::MarkZone&) { return value(); }
};


// service_traits::MD5Sum< ::palletizing::MarkZoneRequest> should match
// service_traits::MD5Sum< ::palletizing::MarkZone >
template<>
struct MD5Sum< ::palletizing::MarkZoneRequest>
{
  static const char* value()
  {
    return MD5Sum< ::palletizing::MarkZone >::value();
  }
  static const char* value(const ::palletizing::MarkZoneRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::palletizing::MarkZoneRequest> should match
// service_traits::DataType< ::palletizing::MarkZone >
template<>
struct DataType< ::palletizing::MarkZoneRequest>
{
  static const char* value()
  {
    return DataType< ::palletizing::MarkZone >::value();
  }
  static const char* value(const ::palletizing::MarkZoneRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::palletizing::MarkZoneResponse> should match
// service_traits::MD5Sum< ::palletizing::MarkZone >
template<>
struct MD5Sum< ::palletizing::MarkZoneResponse>
{
  static const char* value()
  {
    return MD5Sum< ::palletizing::MarkZone >::value();
  }
  static const char* value(const ::palletizing::MarkZoneResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::palletizing::MarkZoneResponse> should match
// service_traits::DataType< ::palletizing::MarkZone >
template<>
struct DataType< ::palletizing::MarkZoneResponse>
{
  static const char* value()
  {
    return DataType< ::palletizing::MarkZone >::value();
  }
  static const char* value(const ::palletizing::MarkZoneResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PALLETIZING_MESSAGE_MARKZONE_H
