// Generated by gencpp from file palletizing/MarkZoneRequest.msg
// DO NOT EDIT!


#ifndef PALLETIZING_MESSAGE_MARKZONEREQUEST_H
#define PALLETIZING_MESSAGE_MARKZONEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace palletizing
{
template <class ContainerAllocator>
struct MarkZoneRequest_
{
  typedef MarkZoneRequest_<ContainerAllocator> Type;

  MarkZoneRequest_()
    : zone_name()
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , yaw(0.0)
    , length(0.0)
    , width(0.0)  {
    }
  MarkZoneRequest_(const ContainerAllocator& _alloc)
    : zone_name(_alloc)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , yaw(0.0)
    , length(0.0)
    , width(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _zone_name_type;
  _zone_name_type zone_name;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _yaw_type;
  _yaw_type yaw;

   typedef double _length_type;
  _length_type length;

   typedef double _width_type;
  _width_type width;





  typedef boost::shared_ptr< ::palletizing::MarkZoneRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::palletizing::MarkZoneRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MarkZoneRequest_

typedef ::palletizing::MarkZoneRequest_<std::allocator<void> > MarkZoneRequest;

typedef boost::shared_ptr< ::palletizing::MarkZoneRequest > MarkZoneRequestPtr;
typedef boost::shared_ptr< ::palletizing::MarkZoneRequest const> MarkZoneRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::palletizing::MarkZoneRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::palletizing::MarkZoneRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::palletizing::MarkZoneRequest_<ContainerAllocator1> & lhs, const ::palletizing::MarkZoneRequest_<ContainerAllocator2> & rhs)
{
  return lhs.zone_name == rhs.zone_name &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.yaw == rhs.yaw &&
    lhs.length == rhs.length &&
    lhs.width == rhs.width;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::palletizing::MarkZoneRequest_<ContainerAllocator1> & lhs, const ::palletizing::MarkZoneRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace palletizing

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::palletizing::MarkZoneRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::palletizing::MarkZoneRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::palletizing::MarkZoneRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::palletizing::MarkZoneRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::palletizing::MarkZoneRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::palletizing::MarkZoneRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::palletizing::MarkZoneRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "69a51bcff6162d7a8b6c4f8ab9edfbd7";
  }

  static const char* value(const ::palletizing::MarkZoneRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x69a51bcff6162d7aULL;
  static const uint64_t static_value2 = 0x8b6c4f8ab9edfbd7ULL;
};

template<class ContainerAllocator>
struct DataType< ::palletizing::MarkZoneRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "palletizing/MarkZoneRequest";
  }

  static const char* value(const ::palletizing::MarkZoneRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::palletizing::MarkZoneRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string zone_name      # 'source' or 'dest'\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 yaw           # 桌面朝向 (radians in /map frame)\n"
"float64 length        # 桌面长度 (沿朝向方向, m)\n"
"float64 width         # 桌面宽度/深度 (垂直朝向方向, m)\n"
;
  }

  static const char* value(const ::palletizing::MarkZoneRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::palletizing::MarkZoneRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.zone_name);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.yaw);
      stream.next(m.length);
      stream.next(m.width);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MarkZoneRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::palletizing::MarkZoneRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::palletizing::MarkZoneRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "zone_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.zone_name);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "length: ";
    Printer<double>::stream(s, indent + "  ", v.length);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "width: ";
    Printer<double>::stream(s, indent + "  ", v.width);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PALLETIZING_MESSAGE_MARKZONEREQUEST_H
