// Generated by gencpp from file palletizing/NavigateFeedback.msg
// DO NOT EDIT!


#ifndef PALLETIZING_MESSAGE_NAVIGATEFEEDBACK_H
#define PALLETIZING_MESSAGE_NAVIGATEFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace palletizing
{
template <class ContainerAllocator>
struct NavigateFeedback_
{
  typedef NavigateFeedback_<ContainerAllocator> Type;

  NavigateFeedback_()
    : distance_remaining(0.0)
    , status()  {
    }
  NavigateFeedback_(const ContainerAllocator& _alloc)
    : distance_remaining(0.0)
    , status(_alloc)  {
  (void)_alloc;
    }



   typedef float _distance_remaining_type;
  _distance_remaining_type distance_remaining;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::palletizing::NavigateFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::palletizing::NavigateFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct NavigateFeedback_

typedef ::palletizing::NavigateFeedback_<std::allocator<void> > NavigateFeedback;

typedef boost::shared_ptr< ::palletizing::NavigateFeedback > NavigateFeedbackPtr;
typedef boost::shared_ptr< ::palletizing::NavigateFeedback const> NavigateFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::palletizing::NavigateFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::palletizing::NavigateFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::palletizing::NavigateFeedback_<ContainerAllocator1> & lhs, const ::palletizing::NavigateFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.distance_remaining == rhs.distance_remaining &&
    lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::palletizing::NavigateFeedback_<ContainerAllocator1> & lhs, const ::palletizing::NavigateFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace palletizing

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::palletizing::NavigateFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::palletizing::NavigateFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::palletizing::NavigateFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::palletizing::NavigateFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::palletizing::NavigateFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::palletizing::NavigateFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::palletizing::NavigateFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "28ebe63659481863c75ff05a435b07a1";
  }

  static const char* value(const ::palletizing::NavigateFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x28ebe63659481863ULL;
  static const uint64_t static_value2 = 0xc75ff05a435b07a1ULL;
};

template<class ContainerAllocator>
struct DataType< ::palletizing::NavigateFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "palletizing/NavigateFeedback";
  }

  static const char* value(const ::palletizing::NavigateFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::palletizing::NavigateFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# ─── Feedback ───\n"
"float32 distance_remaining\n"
"string status\n"
"\n"
;
  }

  static const char* value(const ::palletizing::NavigateFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::palletizing::NavigateFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance_remaining);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavigateFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::palletizing::NavigateFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::palletizing::NavigateFeedback_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "distance_remaining: ";
    Printer<float>::stream(s, indent + "  ", v.distance_remaining);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PALLETIZING_MESSAGE_NAVIGATEFEEDBACK_H
