// Generated by gencpp from file palletizing/NavigateActionGoal.msg
// DO NOT EDIT!


#ifndef PALLETIZING_MESSAGE_NAVIGATEACTIONGOAL_H
#define PALLETIZING_MESSAGE_NAVIGATEACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <palletizing/NavigateGoal.h>

namespace palletizing
{
template <class ContainerAllocator>
struct NavigateActionGoal_
{
  typedef NavigateActionGoal_<ContainerAllocator> Type;

  NavigateActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  NavigateActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::palletizing::NavigateGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::palletizing::NavigateActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::palletizing::NavigateActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct NavigateActionGoal_

typedef ::palletizing::NavigateActionGoal_<std::allocator<void> > NavigateActionGoal;

typedef boost::shared_ptr< ::palletizing::NavigateActionGoal > NavigateActionGoalPtr;
typedef boost::shared_ptr< ::palletizing::NavigateActionGoal const> NavigateActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::palletizing::NavigateActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::palletizing::NavigateActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::palletizing::NavigateActionGoal_<ContainerAllocator1> & lhs, const ::palletizing::NavigateActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::palletizing::NavigateActionGoal_<ContainerAllocator1> & lhs, const ::palletizing::NavigateActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace palletizing

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::palletizing::NavigateActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::palletizing::NavigateActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::palletizing::NavigateActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::palletizing::NavigateActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::palletizing::NavigateActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::palletizing::NavigateActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::palletizing::NavigateActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9f6e7da71bac085b7f5a11c7eb3abbf1";
  }

  static const char* value(const ::palletizing::NavigateActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9f6e7da71bac085bULL;
  static const uint64_t static_value2 = 0x7f5a11c7eb3abbf1ULL;
};

template<class ContainerAllocator>
struct DataType< ::palletizing::NavigateActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "palletizing/NavigateActionGoal";
  }

  static const char* value(const ::palletizing::NavigateActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::palletizing::NavigateActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"NavigateGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: palletizing/NavigateGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# 导航 Action：驱动底盘移动至指定目标点\n"
"# ─── Goal ───\n"
"string target_name\n"
"geometry_msgs/Pose target_pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::palletizing::NavigateActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::palletizing::NavigateActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavigateActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::palletizing::NavigateActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::palletizing::NavigateActionGoal_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "goal_id: ";
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "goal: ";
    Printer< ::palletizing::NavigateGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PALLETIZING_MESSAGE_NAVIGATEACTIONGOAL_H
