// Generated by gencpp from file palletizing/PalletizeGoal.msg
// DO NOT EDIT!


#ifndef PALLETIZING_MESSAGE_PALLETIZEGOAL_H
#define PALLETIZING_MESSAGE_PALLETIZEGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace palletizing
{
template <class ContainerAllocator>
struct PalletizeGoal_
{
  typedef PalletizeGoal_<ContainerAllocator> Type;

  PalletizeGoal_()
    : layer(0)
    , place_position()  {
    }
  PalletizeGoal_(const ContainerAllocator& _alloc)
    : layer(0)
    , place_position(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _layer_type;
  _layer_type layer;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _place_position_type;
  _place_position_type place_position;





  typedef boost::shared_ptr< ::palletizing::PalletizeGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::palletizing::PalletizeGoal_<ContainerAllocator> const> ConstPtr;

}; // struct PalletizeGoal_

typedef ::palletizing::PalletizeGoal_<std::allocator<void> > PalletizeGoal;

typedef boost::shared_ptr< ::palletizing::PalletizeGoal > PalletizeGoalPtr;
typedef boost::shared_ptr< ::palletizing::PalletizeGoal const> PalletizeGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::palletizing::PalletizeGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::palletizing::PalletizeGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::palletizing::PalletizeGoal_<ContainerAllocator1> & lhs, const ::palletizing::PalletizeGoal_<ContainerAllocator2> & rhs)
{
  return lhs.layer == rhs.layer &&
    lhs.place_position == rhs.place_position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::palletizing::PalletizeGoal_<ContainerAllocator1> & lhs, const ::palletizing::PalletizeGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace palletizing

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::palletizing::PalletizeGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::palletizing::PalletizeGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::palletizing::PalletizeGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::palletizing::PalletizeGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::palletizing::PalletizeGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::palletizing::PalletizeGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::palletizing::PalletizeGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ab64145f46649d32273906cef7ee7209";
  }

  static const char* value(const ::palletizing::PalletizeGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xab64145f46649d32ULL;
  static const uint64_t static_value2 = 0x273906cef7ee7209ULL;
};

template<class ContainerAllocator>
struct DataType< ::palletizing::PalletizeGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "palletizing/PalletizeGoal";
  }

  static const char* value(const ::palletizing::PalletizeGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::palletizing::PalletizeGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# 码垛 Action：将货物放置到目标位置（支持多层）\n"
"# ─── Goal ───\n"
"uint8 layer\n"
"geometry_msgs/Point place_position\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::palletizing::PalletizeGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::palletizing::PalletizeGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.layer);
      stream.next(m.place_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PalletizeGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::palletizing::PalletizeGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::palletizing::PalletizeGoal_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "layer: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.layer);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "place_position: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.place_position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PALLETIZING_MESSAGE_PALLETIZEGOAL_H
