// Generated by gencpp from file palletizing/PalletizingStats.msg
// DO NOT EDIT!


#ifndef PALLETIZING_MESSAGE_PALLETIZINGSTATS_H
#define PALLETIZING_MESSAGE_PALLETIZINGSTATS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace palletizing
{
template <class ContainerAllocator>
struct PalletizingStats_
{
  typedef PalletizingStats_<ContainerAllocator> Type;

  PalletizingStats_()
    : total_objects(0)
    , success_count(0)
    , fail_count(0)
    , current_layer(0)
    , hard_zone_layers(0)
    , soft_zone_layers(0)
    , success_rate(0.0)
    , avg_cycle_time(0.0)
    , elapsed_time(0.0)
    , current_state()  {
    }
  PalletizingStats_(const ContainerAllocator& _alloc)
    : total_objects(0)
    , success_count(0)
    , fail_count(0)
    , current_layer(0)
    , hard_zone_layers(0)
    , soft_zone_layers(0)
    , success_rate(0.0)
    , avg_cycle_time(0.0)
    , elapsed_time(0.0)
    , current_state(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _total_objects_type;
  _total_objects_type total_objects;

   typedef uint32_t _success_count_type;
  _success_count_type success_count;

   typedef uint32_t _fail_count_type;
  _fail_count_type fail_count;

   typedef uint32_t _current_layer_type;
  _current_layer_type current_layer;

   typedef uint32_t _hard_zone_layers_type;
  _hard_zone_layers_type hard_zone_layers;

   typedef uint32_t _soft_zone_layers_type;
  _soft_zone_layers_type soft_zone_layers;

   typedef double _success_rate_type;
  _success_rate_type success_rate;

   typedef double _avg_cycle_time_type;
  _avg_cycle_time_type avg_cycle_time;

   typedef double _elapsed_time_type;
  _elapsed_time_type elapsed_time;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _current_state_type;
  _current_state_type current_state;





  typedef boost::shared_ptr< ::palletizing::PalletizingStats_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::palletizing::PalletizingStats_<ContainerAllocator> const> ConstPtr;

}; // struct PalletizingStats_

typedef ::palletizing::PalletizingStats_<std::allocator<void> > PalletizingStats;

typedef boost::shared_ptr< ::palletizing::PalletizingStats > PalletizingStatsPtr;
typedef boost::shared_ptr< ::palletizing::PalletizingStats const> PalletizingStatsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::palletizing::PalletizingStats_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::palletizing::PalletizingStats_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::palletizing::PalletizingStats_<ContainerAllocator1> & lhs, const ::palletizing::PalletizingStats_<ContainerAllocator2> & rhs)
{
  return lhs.total_objects == rhs.total_objects &&
    lhs.success_count == rhs.success_count &&
    lhs.fail_count == rhs.fail_count &&
    lhs.current_layer == rhs.current_layer &&
    lhs.hard_zone_layers == rhs.hard_zone_layers &&
    lhs.soft_zone_layers == rhs.soft_zone_layers &&
    lhs.success_rate == rhs.success_rate &&
    lhs.avg_cycle_time == rhs.avg_cycle_time &&
    lhs.elapsed_time == rhs.elapsed_time &&
    lhs.current_state == rhs.current_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::palletizing::PalletizingStats_<ContainerAllocator1> & lhs, const ::palletizing::PalletizingStats_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace palletizing

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::palletizing::PalletizingStats_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::palletizing::PalletizingStats_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::palletizing::PalletizingStats_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::palletizing::PalletizingStats_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::palletizing::PalletizingStats_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::palletizing::PalletizingStats_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::palletizing::PalletizingStats_<ContainerAllocator> >
{
  static const char* value()
  {
    return "92aa1e36e09f1e3fca1e85e1659ad3fe";
  }

  static const char* value(const ::palletizing::PalletizingStats_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x92aa1e36e09f1e3fULL;
  static const uint64_t static_value2 = 0xca1e85e1659ad3feULL;
};

template<class ContainerAllocator>
struct DataType< ::palletizing::PalletizingStats_<ContainerAllocator> >
{
  static const char* value()
  {
    return "palletizing/PalletizingStats";
  }

  static const char* value(const ::palletizing::PalletizingStats_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::palletizing::PalletizingStats_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 total_objects\n"
"uint32 success_count\n"
"uint32 fail_count\n"
"uint32 current_layer\n"
"uint32 hard_zone_layers\n"
"uint32 soft_zone_layers\n"
"float64 success_rate\n"
"float64 avg_cycle_time\n"
"float64 elapsed_time\n"
"string current_state\n"
;
  }

  static const char* value(const ::palletizing::PalletizingStats_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::palletizing::PalletizingStats_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.total_objects);
      stream.next(m.success_count);
      stream.next(m.fail_count);
      stream.next(m.current_layer);
      stream.next(m.hard_zone_layers);
      stream.next(m.soft_zone_layers);
      stream.next(m.success_rate);
      stream.next(m.avg_cycle_time);
      stream.next(m.elapsed_time);
      stream.next(m.current_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PalletizingStats_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::palletizing::PalletizingStats_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::palletizing::PalletizingStats_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "total_objects: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.total_objects);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "success_count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.success_count);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fail_count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.fail_count);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "current_layer: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.current_layer);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "hard_zone_layers: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.hard_zone_layers);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "soft_zone_layers: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.soft_zone_layers);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "success_rate: ";
    Printer<double>::stream(s, indent + "  ", v.success_rate);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "avg_cycle_time: ";
    Printer<double>::stream(s, indent + "  ", v.avg_cycle_time);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "elapsed_time: ";
    Printer<double>::stream(s, indent + "  ", v.elapsed_time);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "current_state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.current_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PALLETIZING_MESSAGE_PALLETIZINGSTATS_H
