// Generated by gencpp from file palletizing/SafetyStatus.msg
// DO NOT EDIT!


#ifndef PALLETIZING_MESSAGE_SAFETYSTATUS_H
#define PALLETIZING_MESSAGE_SAFETYSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace palletizing
{
template <class ContainerAllocator>
struct SafetyStatus_
{
  typedef SafetyStatus_<ContainerAllocator> Type;

  SafetyStatus_()
    : level(0)
    , min_distance(0.0)
    , message()  {
    }
  SafetyStatus_(const ContainerAllocator& _alloc)
    : level(0)
    , min_distance(0.0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _level_type;
  _level_type level;

   typedef double _min_distance_type;
  _min_distance_type min_distance;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(CLEAR)
  #undef CLEAR
#endif
#if defined(_WIN32) && defined(WARNING)
  #undef WARNING
#endif
#if defined(_WIN32) && defined(EMERGENCY)
  #undef EMERGENCY
#endif

  enum {
    CLEAR = 0u,
    WARNING = 1u,
    EMERGENCY = 2u,
  };


  typedef boost::shared_ptr< ::palletizing::SafetyStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::palletizing::SafetyStatus_<ContainerAllocator> const> ConstPtr;

}; // struct SafetyStatus_

typedef ::palletizing::SafetyStatus_<std::allocator<void> > SafetyStatus;

typedef boost::shared_ptr< ::palletizing::SafetyStatus > SafetyStatusPtr;
typedef boost::shared_ptr< ::palletizing::SafetyStatus const> SafetyStatusConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::palletizing::SafetyStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::palletizing::SafetyStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::palletizing::SafetyStatus_<ContainerAllocator1> & lhs, const ::palletizing::SafetyStatus_<ContainerAllocator2> & rhs)
{
  return lhs.level == rhs.level &&
    lhs.min_distance == rhs.min_distance &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::palletizing::SafetyStatus_<ContainerAllocator1> & lhs, const ::palletizing::SafetyStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace palletizing

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::palletizing::SafetyStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::palletizing::SafetyStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::palletizing::SafetyStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::palletizing::SafetyStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::palletizing::SafetyStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::palletizing::SafetyStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::palletizing::SafetyStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "080f944521045f84e22d6ce4b4a77218";
  }

  static const char* value(const ::palletizing::SafetyStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x080f944521045f84ULL;
  static const uint64_t static_value2 = 0xe22d6ce4b4a77218ULL;
};

template<class ContainerAllocator>
struct DataType< ::palletizing::SafetyStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "palletizing/SafetyStatus";
  }

  static const char* value(const ::palletizing::SafetyStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::palletizing::SafetyStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 CLEAR=0\n"
"uint8 WARNING=1\n"
"uint8 EMERGENCY=2\n"
"uint8 level\n"
"float64 min_distance\n"
"string message\n"
;
  }

  static const char* value(const ::palletizing::SafetyStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::palletizing::SafetyStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.level);
      stream.next(m.min_distance);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SafetyStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::palletizing::SafetyStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::palletizing::SafetyStatus_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "level: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.level);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "min_distance: ";
    Printer<double>::stream(s, indent + "  ", v.min_distance);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PALLETIZING_MESSAGE_SAFETYSTATUS_H
