// Generated by gencpp from file palletizing/StartTaskRequest.msg
// DO NOT EDIT!


#ifndef PALLETIZING_MESSAGE_STARTTASKREQUEST_H
#define PALLETIZING_MESSAGE_STARTTASKREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace palletizing
{
template <class ContainerAllocator>
struct StartTaskRequest_
{
  typedef StartTaskRequest_<ContainerAllocator> Type;

  StartTaskRequest_()
    {
    }
  StartTaskRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::palletizing::StartTaskRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::palletizing::StartTaskRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StartTaskRequest_

typedef ::palletizing::StartTaskRequest_<std::allocator<void> > StartTaskRequest;

typedef boost::shared_ptr< ::palletizing::StartTaskRequest > StartTaskRequestPtr;
typedef boost::shared_ptr< ::palletizing::StartTaskRequest const> StartTaskRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::palletizing::StartTaskRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::palletizing::StartTaskRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace palletizing

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::palletizing::StartTaskRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::palletizing::StartTaskRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::palletizing::StartTaskRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::palletizing::StartTaskRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::palletizing::StartTaskRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::palletizing::StartTaskRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::palletizing::StartTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::palletizing::StartTaskRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::palletizing::StartTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "palletizing/StartTaskRequest";
  }

  static const char* value(const ::palletizing::StartTaskRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::palletizing::StartTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::palletizing::StartTaskRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::palletizing::StartTaskRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartTaskRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::palletizing::StartTaskRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::palletizing::StartTaskRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // PALLETIZING_MESSAGE_STARTTASKREQUEST_H
