// Generated by gencpp from file palletizing/StartTask.msg
// DO NOT EDIT!


#ifndef PALLETIZING_MESSAGE_STARTTASK_H
#define PALLETIZING_MESSAGE_STARTTASK_H

#include <ros/service_traits.h>


#include <palletizing/StartTaskRequest.h>
#include <palletizing/StartTaskResponse.h>


namespace palletizing
{

struct StartTask
{

typedef StartTaskRequest Request;
typedef StartTaskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StartTask
} // namespace palletizing


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::palletizing::StartTask > {
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::palletizing::StartTask&) { return value(); }
};

template<>
struct DataType< ::palletizing::StartTask > {
  static const char* value()
  {
    return "palletizing/StartTask";
  }

  static const char* value(const ::palletizing::StartTask&) { return value(); }
};


// service_traits::MD5Sum< ::palletizing::StartTaskRequest> should match
// service_traits::MD5Sum< ::palletizing::StartTask >
template<>
struct MD5Sum< ::palletizing::StartTaskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::palletizing::StartTask >::value();
  }
  static const char* value(const ::palletizing::StartTaskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::palletizing::StartTaskRequest> should match
// service_traits::DataType< ::palletizing::StartTask >
template<>
struct DataType< ::palletizing::StartTaskRequest>
{
  static const char* value()
  {
    return DataType< ::palletizing::StartTask >::value();
  }
  static const char* value(const ::palletizing::StartTaskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::palletizing::StartTaskResponse> should match
// service_traits::MD5Sum< ::palletizing::StartTask >
template<>
struct MD5Sum< ::palletizing::StartTaskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::palletizing::StartTask >::value();
  }
  static const char* value(const ::palletizing::StartTaskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::palletizing::StartTaskResponse> should match
// service_traits::DataType< ::palletizing::StartTask >
template<>
struct DataType< ::palletizing::StartTaskResponse>
{
  static const char* value()
  {
    return DataType< ::palletizing::StartTask >::value();
  }
  static const char* value(const ::palletizing::StartTaskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PALLETIZING_MESSAGE_STARTTASK_H
