// Generated by gencpp from file palletizing/SystemReset.msg
// DO NOT EDIT!


#ifndef PALLETIZING_MESSAGE_SYSTEMRESET_H
#define PALLETIZING_MESSAGE_SYSTEMRESET_H

#include <ros/service_traits.h>


#include <palletizing/SystemResetRequest.h>
#include <palletizing/SystemResetResponse.h>


namespace palletizing
{

struct SystemReset
{

typedef SystemResetRequest Request;
typedef SystemResetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SystemReset
} // namespace palletizing


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::palletizing::SystemReset > {
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::palletizing::SystemReset&) { return value(); }
};

template<>
struct DataType< ::palletizing::SystemReset > {
  static const char* value()
  {
    return "palletizing/SystemReset";
  }

  static const char* value(const ::palletizing::SystemReset&) { return value(); }
};


// service_traits::MD5Sum< ::palletizing::SystemResetRequest> should match
// service_traits::MD5Sum< ::palletizing::SystemReset >
template<>
struct MD5Sum< ::palletizing::SystemResetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::palletizing::SystemReset >::value();
  }
  static const char* value(const ::palletizing::SystemResetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::palletizing::SystemResetRequest> should match
// service_traits::DataType< ::palletizing::SystemReset >
template<>
struct DataType< ::palletizing::SystemResetRequest>
{
  static const char* value()
  {
    return DataType< ::palletizing::SystemReset >::value();
  }
  static const char* value(const ::palletizing::SystemResetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::palletizing::SystemResetResponse> should match
// service_traits::MD5Sum< ::palletizing::SystemReset >
template<>
struct MD5Sum< ::palletizing::SystemResetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::palletizing::SystemReset >::value();
  }
  static const char* value(const ::palletizing::SystemResetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::palletizing::SystemResetResponse> should match
// service_traits::DataType< ::palletizing::SystemReset >
template<>
struct DataType< ::palletizing::SystemResetResponse>
{
  static const char* value()
  {
    return DataType< ::palletizing::SystemReset >::value();
  }
  static const char* value(const ::palletizing::SystemResetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PALLETIZING_MESSAGE_SYSTEMRESET_H
