// Generated by gencpp from file palletizing/TriggerDetectionRequest.msg
// DO NOT EDIT!


#ifndef PALLETIZING_MESSAGE_TRIGGERDETECTIONREQUEST_H
#define PALLETIZING_MESSAGE_TRIGGERDETECTIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace palletizing
{
template <class ContainerAllocator>
struct TriggerDetectionRequest_
{
  typedef TriggerDetectionRequest_<ContainerAllocator> Type;

  TriggerDetectionRequest_()
    : cargo_type()  {
    }
  TriggerDetectionRequest_(const ContainerAllocator& _alloc)
    : cargo_type(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _cargo_type_type;
  _cargo_type_type cargo_type;





  typedef boost::shared_ptr< ::palletizing::TriggerDetectionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::palletizing::TriggerDetectionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TriggerDetectionRequest_

typedef ::palletizing::TriggerDetectionRequest_<std::allocator<void> > TriggerDetectionRequest;

typedef boost::shared_ptr< ::palletizing::TriggerDetectionRequest > TriggerDetectionRequestPtr;
typedef boost::shared_ptr< ::palletizing::TriggerDetectionRequest const> TriggerDetectionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::palletizing::TriggerDetectionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::palletizing::TriggerDetectionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::palletizing::TriggerDetectionRequest_<ContainerAllocator1> & lhs, const ::palletizing::TriggerDetectionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.cargo_type == rhs.cargo_type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::palletizing::TriggerDetectionRequest_<ContainerAllocator1> & lhs, const ::palletizing::TriggerDetectionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace palletizing

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::palletizing::TriggerDetectionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::palletizing::TriggerDetectionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::palletizing::TriggerDetectionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::palletizing::TriggerDetectionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::palletizing::TriggerDetectionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::palletizing::TriggerDetectionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::palletizing::TriggerDetectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d8d3ec2048ffb969c4596e0ec3aef25b";
  }

  static const char* value(const ::palletizing::TriggerDetectionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd8d3ec2048ffb969ULL;
  static const uint64_t static_value2 = 0xc4596e0ec3aef25bULL;
};

template<class ContainerAllocator>
struct DataType< ::palletizing::TriggerDetectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "palletizing/TriggerDetectionRequest";
  }

  static const char* value(const ::palletizing::TriggerDetectionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::palletizing::TriggerDetectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 触发单次视觉识别服务\n"
"# 请求：货物类型\n"
"string cargo_type\n"
;
  }

  static const char* value(const ::palletizing::TriggerDetectionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::palletizing::TriggerDetectionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cargo_type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TriggerDetectionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::palletizing::TriggerDetectionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::palletizing::TriggerDetectionRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "cargo_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.cargo_type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PALLETIZING_MESSAGE_TRIGGERDETECTIONREQUEST_H
