// Generated by gencpp from file palletizing/TriggerDetection.msg
// DO NOT EDIT!


#ifndef PALLETIZING_MESSAGE_TRIGGERDETECTION_H
#define PALLETIZING_MESSAGE_TRIGGERDETECTION_H

#include <ros/service_traits.h>


#include <palletizing/TriggerDetectionRequest.h>
#include <palletizing/TriggerDetectionResponse.h>


namespace palletizing
{

struct TriggerDetection
{

typedef TriggerDetectionRequest Request;
typedef TriggerDetectionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TriggerDetection
} // namespace palletizing


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::palletizing::TriggerDetection > {
  static const char* value()
  {
    return "36866cc854ee48ffadf2fd965e06457e";
  }

  static const char* value(const ::palletizing::TriggerDetection&) { return value(); }
};

template<>
struct DataType< ::palletizing::TriggerDetection > {
  static const char* value()
  {
    return "palletizing/TriggerDetection";
  }

  static const char* value(const ::palletizing::TriggerDetection&) { return value(); }
};


// service_traits::MD5Sum< ::palletizing::TriggerDetectionRequest> should match
// service_traits::MD5Sum< ::palletizing::TriggerDetection >
template<>
struct MD5Sum< ::palletizing::TriggerDetectionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::palletizing::TriggerDetection >::value();
  }
  static const char* value(const ::palletizing::TriggerDetectionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::palletizing::TriggerDetectionRequest> should match
// service_traits::DataType< ::palletizing::TriggerDetection >
template<>
struct DataType< ::palletizing::TriggerDetectionRequest>
{
  static const char* value()
  {
    return DataType< ::palletizing::TriggerDetection >::value();
  }
  static const char* value(const ::palletizing::TriggerDetectionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::palletizing::TriggerDetectionResponse> should match
// service_traits::MD5Sum< ::palletizing::TriggerDetection >
template<>
struct MD5Sum< ::palletizing::TriggerDetectionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::palletizing::TriggerDetection >::value();
  }
  static const char* value(const ::palletizing::TriggerDetectionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::palletizing::TriggerDetectionResponse> should match
// service_traits::DataType< ::palletizing::TriggerDetection >
template<>
struct DataType< ::palletizing::TriggerDetectionResponse>
{
  static const char* value()
  {
    return DataType< ::palletizing::TriggerDetection >::value();
  }
  static const char* value(const ::palletizing::TriggerDetectionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PALLETIZING_MESSAGE_TRIGGERDETECTION_H
