// Generated by gencpp from file palletizing/TriggerDetectionResponse.msg
// DO NOT EDIT!


#ifndef PALLETIZING_MESSAGE_TRIGGERDETECTIONRESPONSE_H
#define PALLETIZING_MESSAGE_TRIGGERDETECTIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace palletizing
{
template <class ContainerAllocator>
struct TriggerDetectionResponse_
{
  typedef TriggerDetectionResponse_<ContainerAllocator> Type;

  TriggerDetectionResponse_()
    : success(false)
    , message()
    , position()
    , remaining_count(0)  {
    }
  TriggerDetectionResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)
    , position(_alloc)
    , remaining_count(0)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef int32_t _remaining_count_type;
  _remaining_count_type remaining_count;





  typedef boost::shared_ptr< ::palletizing::TriggerDetectionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::palletizing::TriggerDetectionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TriggerDetectionResponse_

typedef ::palletizing::TriggerDetectionResponse_<std::allocator<void> > TriggerDetectionResponse;

typedef boost::shared_ptr< ::palletizing::TriggerDetectionResponse > TriggerDetectionResponsePtr;
typedef boost::shared_ptr< ::palletizing::TriggerDetectionResponse const> TriggerDetectionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::palletizing::TriggerDetectionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::palletizing::TriggerDetectionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::palletizing::TriggerDetectionResponse_<ContainerAllocator1> & lhs, const ::palletizing::TriggerDetectionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message &&
    lhs.position == rhs.position &&
    lhs.remaining_count == rhs.remaining_count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::palletizing::TriggerDetectionResponse_<ContainerAllocator1> & lhs, const ::palletizing::TriggerDetectionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace palletizing

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::palletizing::TriggerDetectionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::palletizing::TriggerDetectionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::palletizing::TriggerDetectionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::palletizing::TriggerDetectionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::palletizing::TriggerDetectionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::palletizing::TriggerDetectionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::palletizing::TriggerDetectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f5c9adf66f15c230ef796894d4b95eca";
  }

  static const char* value(const ::palletizing::TriggerDetectionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf5c9adf66f15c230ULL;
  static const uint64_t static_value2 = 0xef796894d4b95ecaULL;
};

template<class ContainerAllocator>
struct DataType< ::palletizing::TriggerDetectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "palletizing/TriggerDetectionResponse";
  }

  static const char* value(const ::palletizing::TriggerDetectionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::palletizing::TriggerDetectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 响应：是否成功、目标在 base_link 坐标系下的三维坐标\n"
"bool success\n"
"string message\n"
"geometry_msgs/Point position\n"
"int32 remaining_count\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::palletizing::TriggerDetectionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::palletizing::TriggerDetectionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
      stream.next(m.position);
      stream.next(m.remaining_count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TriggerDetectionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::palletizing::TriggerDetectionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::palletizing::TriggerDetectionResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "position: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "remaining_count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.remaining_count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PALLETIZING_MESSAGE_TRIGGERDETECTIONRESPONSE_H
