<?xml version="1.0"?>
<package format="2">
  <name>warehouse_sorting</name>
  <version>0.1.0</version>
  <description>Warehouse cargo sorting and palletizing nodes for ROS Noetic.</description>
  <maintainer email="robot@todo.todo">Monday Team 2</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>geometry_msgs</build_depend>
  <build_depend>rospy</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>std_srvs</build_depend>
  <build_depend>warehouse_sorting_msgs</build_depend>

  <build_export_depend>geometry_msgs</build_export_depend>
  <build_export_depend>rospy</build_export_depend>
  <build_export_depend>sensor_msgs</build_export_depend>
  <build_export_depend>std_msgs</build_export_depend>
  <build_export_depend>std_srvs</build_export_depend>
  <build_export_depend>warehouse_sorting_msgs</build_export_depend>

  <exec_depend>actionlib</exec_depend>
  <exec_depend>actionlib_msgs</exec_depend>
  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>move_base_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>rospy</exec_depend>
  <exec_depend>rosbridge_server</exec_depend>
  <exec_depend>rospack</exec_depend>
  <exec_depend>rosservice</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>std_srvs</exec_depend>
  <exec_depend>tf</exec_depend>
  <exec_depend>warehouse_sorting_msgs</exec_depend>
  <exec_depend>web_video_server</exec_depend>
  <exec_depend>wpb_home_behaviors</exec_depend>

  <test_depend>python3-nose</test_depend>

  <export>
  </export>
</package>
