zeros:
  kinect_height: 1.32
  kinect_pitch: -0.61

camera_mount:
  x: 0.170
  y: -0.100
  z: 0.0

grab:
  grab_y_offset: 0.0
  grab_lift_offset: 0.0
  grab_forward_offset: 0.0
  grab_gripper_value: 0.035
  grab_hand_up_wait: 4.0
