// Generated by gencpp from file vizanti/GetNodeParametersRequest.msg
// DO NOT EDIT!


#ifndef VIZANTI_MESSAGE_GETNODEPARAMETERSREQUEST_H
#define VIZANTI_MESSAGE_GETNODEPARAMETERSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vizanti
{
template <class ContainerAllocator>
struct GetNodeParametersRequest_
{
  typedef GetNodeParametersRequest_<ContainerAllocator> Type;

  GetNodeParametersRequest_()
    : node()  {
    }
  GetNodeParametersRequest_(const ContainerAllocator& _alloc)
    : node(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _node_type;
  _node_type node;





  typedef boost::shared_ptr< ::vizanti::GetNodeParametersRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vizanti::GetNodeParametersRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetNodeParametersRequest_

typedef ::vizanti::GetNodeParametersRequest_<std::allocator<void> > GetNodeParametersRequest;

typedef boost::shared_ptr< ::vizanti::GetNodeParametersRequest > GetNodeParametersRequestPtr;
typedef boost::shared_ptr< ::vizanti::GetNodeParametersRequest const> GetNodeParametersRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vizanti::GetNodeParametersRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vizanti::GetNodeParametersRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vizanti::GetNodeParametersRequest_<ContainerAllocator1> & lhs, const ::vizanti::GetNodeParametersRequest_<ContainerAllocator2> & rhs)
{
  return lhs.node == rhs.node;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vizanti::GetNodeParametersRequest_<ContainerAllocator1> & lhs, const ::vizanti::GetNodeParametersRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vizanti

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vizanti::GetNodeParametersRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vizanti::GetNodeParametersRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vizanti::GetNodeParametersRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vizanti::GetNodeParametersRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vizanti::GetNodeParametersRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vizanti::GetNodeParametersRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vizanti::GetNodeParametersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a94c40e70a4b82863e6e52ec16732447";
  }

  static const char* value(const ::vizanti::GetNodeParametersRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa94c40e70a4b8286ULL;
  static const uint64_t static_value2 = 0x3e6e52ec16732447ULL;
};

template<class ContainerAllocator>
struct DataType< ::vizanti::GetNodeParametersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vizanti/GetNodeParametersRequest";
  }

  static const char* value(const ::vizanti::GetNodeParametersRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vizanti::GetNodeParametersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string node\n"
;
  }

  static const char* value(const ::vizanti::GetNodeParametersRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vizanti::GetNodeParametersRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.node);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetNodeParametersRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vizanti::GetNodeParametersRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vizanti::GetNodeParametersRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "node: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.node);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VIZANTI_MESSAGE_GETNODEPARAMETERSREQUEST_H
