// Generated by gencpp from file vizanti/GetNodeParametersResponse.msg
// DO NOT EDIT!


#ifndef VIZANTI_MESSAGE_GETNODEPARAMETERSRESPONSE_H
#define VIZANTI_MESSAGE_GETNODEPARAMETERSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vizanti
{
template <class ContainerAllocator>
struct GetNodeParametersResponse_
{
  typedef GetNodeParametersResponse_<ContainerAllocator> Type;

  GetNodeParametersResponse_()
    : parameters()  {
    }
  GetNodeParametersResponse_(const ContainerAllocator& _alloc)
    : parameters(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _parameters_type;
  _parameters_type parameters;





  typedef boost::shared_ptr< ::vizanti::GetNodeParametersResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vizanti::GetNodeParametersResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetNodeParametersResponse_

typedef ::vizanti::GetNodeParametersResponse_<std::allocator<void> > GetNodeParametersResponse;

typedef boost::shared_ptr< ::vizanti::GetNodeParametersResponse > GetNodeParametersResponsePtr;
typedef boost::shared_ptr< ::vizanti::GetNodeParametersResponse const> GetNodeParametersResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vizanti::GetNodeParametersResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vizanti::GetNodeParametersResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vizanti::GetNodeParametersResponse_<ContainerAllocator1> & lhs, const ::vizanti::GetNodeParametersResponse_<ContainerAllocator2> & rhs)
{
  return lhs.parameters == rhs.parameters;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vizanti::GetNodeParametersResponse_<ContainerAllocator1> & lhs, const ::vizanti::GetNodeParametersResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vizanti

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vizanti::GetNodeParametersResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vizanti::GetNodeParametersResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vizanti::GetNodeParametersResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vizanti::GetNodeParametersResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vizanti::GetNodeParametersResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vizanti::GetNodeParametersResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vizanti::GetNodeParametersResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b96cd7929ab82d8413ba620379c440ce";
  }

  static const char* value(const ::vizanti::GetNodeParametersResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb96cd7929ab82d84ULL;
  static const uint64_t static_value2 = 0x13ba620379c440ceULL;
};

template<class ContainerAllocator>
struct DataType< ::vizanti::GetNodeParametersResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vizanti/GetNodeParametersResponse";
  }

  static const char* value(const ::vizanti::GetNodeParametersResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vizanti::GetNodeParametersResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string parameters\n"
;
  }

  static const char* value(const ::vizanti::GetNodeParametersResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vizanti::GetNodeParametersResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.parameters);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetNodeParametersResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vizanti::GetNodeParametersResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vizanti::GetNodeParametersResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "parameters: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.parameters);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VIZANTI_MESSAGE_GETNODEPARAMETERSRESPONSE_H
