// Generated by gencpp from file vizanti/ListExecutablesResponse.msg
// DO NOT EDIT!


#ifndef VIZANTI_MESSAGE_LISTEXECUTABLESRESPONSE_H
#define VIZANTI_MESSAGE_LISTEXECUTABLESRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vizanti
{
template <class ContainerAllocator>
struct ListExecutablesResponse_
{
  typedef ListExecutablesResponse_<ContainerAllocator> Type;

  ListExecutablesResponse_()
    : executables()  {
    }
  ListExecutablesResponse_(const ContainerAllocator& _alloc)
    : executables(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _executables_type;
  _executables_type executables;





  typedef boost::shared_ptr< ::vizanti::ListExecutablesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vizanti::ListExecutablesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ListExecutablesResponse_

typedef ::vizanti::ListExecutablesResponse_<std::allocator<void> > ListExecutablesResponse;

typedef boost::shared_ptr< ::vizanti::ListExecutablesResponse > ListExecutablesResponsePtr;
typedef boost::shared_ptr< ::vizanti::ListExecutablesResponse const> ListExecutablesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vizanti::ListExecutablesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vizanti::ListExecutablesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vizanti::ListExecutablesResponse_<ContainerAllocator1> & lhs, const ::vizanti::ListExecutablesResponse_<ContainerAllocator2> & rhs)
{
  return lhs.executables == rhs.executables;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vizanti::ListExecutablesResponse_<ContainerAllocator1> & lhs, const ::vizanti::ListExecutablesResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vizanti

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vizanti::ListExecutablesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vizanti::ListExecutablesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vizanti::ListExecutablesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vizanti::ListExecutablesResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vizanti::ListExecutablesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vizanti::ListExecutablesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vizanti::ListExecutablesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ab0610255ac01d1e2184dfc9f7f7ed73";
  }

  static const char* value(const ::vizanti::ListExecutablesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xab0610255ac01d1eULL;
  static const uint64_t static_value2 = 0x2184dfc9f7f7ed73ULL;
};

template<class ContainerAllocator>
struct DataType< ::vizanti::ListExecutablesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vizanti/ListExecutablesResponse";
  }

  static const char* value(const ::vizanti::ListExecutablesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vizanti::ListExecutablesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] executables \n"
"\n"
;
  }

  static const char* value(const ::vizanti::ListExecutablesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vizanti::ListExecutablesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.executables);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ListExecutablesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vizanti::ListExecutablesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vizanti::ListExecutablesResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "executables: ";
    if (v.executables.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.executables.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, true ? std::string() : indent + "    ", v.executables[i]);
    }
    if (v.executables.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // VIZANTI_MESSAGE_LISTEXECUTABLESRESPONSE_H
