// Generated by gencpp from file vizanti/ListExecutables.msg
// DO NOT EDIT!


#ifndef VIZANTI_MESSAGE_LISTEXECUTABLES_H
#define VIZANTI_MESSAGE_LISTEXECUTABLES_H

#include <ros/service_traits.h>


#include <vizanti/ListExecutablesRequest.h>
#include <vizanti/ListExecutablesResponse.h>


namespace vizanti
{

struct ListExecutables
{

typedef ListExecutablesRequest Request;
typedef ListExecutablesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ListExecutables
} // namespace vizanti


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vizanti::ListExecutables > {
  static const char* value()
  {
    return "0d9dadc8a6139fd3d3c4c0b768c8f47c";
  }

  static const char* value(const ::vizanti::ListExecutables&) { return value(); }
};

template<>
struct DataType< ::vizanti::ListExecutables > {
  static const char* value()
  {
    return "vizanti/ListExecutables";
  }

  static const char* value(const ::vizanti::ListExecutables&) { return value(); }
};


// service_traits::MD5Sum< ::vizanti::ListExecutablesRequest> should match
// service_traits::MD5Sum< ::vizanti::ListExecutables >
template<>
struct MD5Sum< ::vizanti::ListExecutablesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vizanti::ListExecutables >::value();
  }
  static const char* value(const ::vizanti::ListExecutablesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vizanti::ListExecutablesRequest> should match
// service_traits::DataType< ::vizanti::ListExecutables >
template<>
struct DataType< ::vizanti::ListExecutablesRequest>
{
  static const char* value()
  {
    return DataType< ::vizanti::ListExecutables >::value();
  }
  static const char* value(const ::vizanti::ListExecutablesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vizanti::ListExecutablesResponse> should match
// service_traits::MD5Sum< ::vizanti::ListExecutables >
template<>
struct MD5Sum< ::vizanti::ListExecutablesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vizanti::ListExecutables >::value();
  }
  static const char* value(const ::vizanti::ListExecutablesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vizanti::ListExecutablesResponse> should match
// service_traits::DataType< ::vizanti::ListExecutables >
template<>
struct DataType< ::vizanti::ListExecutablesResponse>
{
  static const char* value()
  {
    return DataType< ::vizanti::ListExecutables >::value();
  }
  static const char* value(const ::vizanti::ListExecutablesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VIZANTI_MESSAGE_LISTEXECUTABLES_H
