// Generated by gencpp from file vizanti/ListPackages.msg
// DO NOT EDIT!


#ifndef VIZANTI_MESSAGE_LISTPACKAGES_H
#define VIZANTI_MESSAGE_LISTPACKAGES_H

#include <ros/service_traits.h>


#include <vizanti/ListPackagesRequest.h>
#include <vizanti/ListPackagesResponse.h>


namespace vizanti
{

struct ListPackages
{

typedef ListPackagesRequest Request;
typedef ListPackagesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ListPackages
} // namespace vizanti


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vizanti::ListPackages > {
  static const char* value()
  {
    return "16e658dd9a0c0812bd000a8e17c5f7b4";
  }

  static const char* value(const ::vizanti::ListPackages&) { return value(); }
};

template<>
struct DataType< ::vizanti::ListPackages > {
  static const char* value()
  {
    return "vizanti/ListPackages";
  }

  static const char* value(const ::vizanti::ListPackages&) { return value(); }
};


// service_traits::MD5Sum< ::vizanti::ListPackagesRequest> should match
// service_traits::MD5Sum< ::vizanti::ListPackages >
template<>
struct MD5Sum< ::vizanti::ListPackagesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vizanti::ListPackages >::value();
  }
  static const char* value(const ::vizanti::ListPackagesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vizanti::ListPackagesRequest> should match
// service_traits::DataType< ::vizanti::ListPackages >
template<>
struct DataType< ::vizanti::ListPackagesRequest>
{
  static const char* value()
  {
    return DataType< ::vizanti::ListPackages >::value();
  }
  static const char* value(const ::vizanti::ListPackagesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vizanti::ListPackagesResponse> should match
// service_traits::MD5Sum< ::vizanti::ListPackages >
template<>
struct MD5Sum< ::vizanti::ListPackagesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vizanti::ListPackages >::value();
  }
  static const char* value(const ::vizanti::ListPackagesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vizanti::ListPackagesResponse> should match
// service_traits::DataType< ::vizanti::ListPackages >
template<>
struct DataType< ::vizanti::ListPackagesResponse>
{
  static const char* value()
  {
    return DataType< ::vizanti::ListPackages >::value();
  }
  static const char* value(const ::vizanti::ListPackagesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VIZANTI_MESSAGE_LISTPACKAGES_H
