// Generated by gencpp from file vizanti/LoadMap.msg
// DO NOT EDIT!


#ifndef VIZANTI_MESSAGE_LOADMAP_H
#define VIZANTI_MESSAGE_LOADMAP_H

#include <ros/service_traits.h>


#include <vizanti/LoadMapRequest.h>
#include <vizanti/LoadMapResponse.h>


namespace vizanti
{

struct LoadMap
{

typedef LoadMapRequest Request;
typedef LoadMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LoadMap
} // namespace vizanti


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vizanti::LoadMap > {
  static const char* value()
  {
    return "46e31fc20e6d3bc78598163aa51c13bd";
  }

  static const char* value(const ::vizanti::LoadMap&) { return value(); }
};

template<>
struct DataType< ::vizanti::LoadMap > {
  static const char* value()
  {
    return "vizanti/LoadMap";
  }

  static const char* value(const ::vizanti::LoadMap&) { return value(); }
};


// service_traits::MD5Sum< ::vizanti::LoadMapRequest> should match
// service_traits::MD5Sum< ::vizanti::LoadMap >
template<>
struct MD5Sum< ::vizanti::LoadMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vizanti::LoadMap >::value();
  }
  static const char* value(const ::vizanti::LoadMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vizanti::LoadMapRequest> should match
// service_traits::DataType< ::vizanti::LoadMap >
template<>
struct DataType< ::vizanti::LoadMapRequest>
{
  static const char* value()
  {
    return DataType< ::vizanti::LoadMap >::value();
  }
  static const char* value(const ::vizanti::LoadMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vizanti::LoadMapResponse> should match
// service_traits::MD5Sum< ::vizanti::LoadMap >
template<>
struct MD5Sum< ::vizanti::LoadMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vizanti::LoadMap >::value();
  }
  static const char* value(const ::vizanti::LoadMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vizanti::LoadMapResponse> should match
// service_traits::DataType< ::vizanti::LoadMap >
template<>
struct DataType< ::vizanti::LoadMapResponse>
{
  static const char* value()
  {
    return DataType< ::vizanti::LoadMap >::value();
  }
  static const char* value(const ::vizanti::LoadMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VIZANTI_MESSAGE_LOADMAP_H
