// Generated by gencpp from file vizanti/RecordRosbag.msg
// DO NOT EDIT!


#ifndef VIZANTI_MESSAGE_RECORDROSBAG_H
#define VIZANTI_MESSAGE_RECORDROSBAG_H

#include <ros/service_traits.h>


#include <vizanti/RecordRosbagRequest.h>
#include <vizanti/RecordRosbagResponse.h>


namespace vizanti
{

struct RecordRosbag
{

typedef RecordRosbagRequest Request;
typedef RecordRosbagResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RecordRosbag
} // namespace vizanti


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vizanti::RecordRosbag > {
  static const char* value()
  {
    return "292a2bef14171aa396b7aff9a49b098c";
  }

  static const char* value(const ::vizanti::RecordRosbag&) { return value(); }
};

template<>
struct DataType< ::vizanti::RecordRosbag > {
  static const char* value()
  {
    return "vizanti/RecordRosbag";
  }

  static const char* value(const ::vizanti::RecordRosbag&) { return value(); }
};


// service_traits::MD5Sum< ::vizanti::RecordRosbagRequest> should match
// service_traits::MD5Sum< ::vizanti::RecordRosbag >
template<>
struct MD5Sum< ::vizanti::RecordRosbagRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vizanti::RecordRosbag >::value();
  }
  static const char* value(const ::vizanti::RecordRosbagRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vizanti::RecordRosbagRequest> should match
// service_traits::DataType< ::vizanti::RecordRosbag >
template<>
struct DataType< ::vizanti::RecordRosbagRequest>
{
  static const char* value()
  {
    return DataType< ::vizanti::RecordRosbag >::value();
  }
  static const char* value(const ::vizanti::RecordRosbagRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vizanti::RecordRosbagResponse> should match
// service_traits::MD5Sum< ::vizanti::RecordRosbag >
template<>
struct MD5Sum< ::vizanti::RecordRosbagResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vizanti::RecordRosbag >::value();
  }
  static const char* value(const ::vizanti::RecordRosbagResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vizanti::RecordRosbagResponse> should match
// service_traits::DataType< ::vizanti::RecordRosbag >
template<>
struct DataType< ::vizanti::RecordRosbagResponse>
{
  static const char* value()
  {
    return DataType< ::vizanti::RecordRosbag >::value();
  }
  static const char* value(const ::vizanti::RecordRosbagResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VIZANTI_MESSAGE_RECORDROSBAG_H
