// Generated by gencpp from file vizanti/SaveMapRequest.msg
// DO NOT EDIT!


#ifndef VIZANTI_MESSAGE_SAVEMAPREQUEST_H
#define VIZANTI_MESSAGE_SAVEMAPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vizanti
{
template <class ContainerAllocator>
struct SaveMapRequest_
{
  typedef SaveMapRequest_<ContainerAllocator> Type;

  SaveMapRequest_()
    : file_path()
    , topic()  {
    }
  SaveMapRequest_(const ContainerAllocator& _alloc)
    : file_path(_alloc)
    , topic(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _file_path_type;
  _file_path_type file_path;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _topic_type;
  _topic_type topic;





  typedef boost::shared_ptr< ::vizanti::SaveMapRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vizanti::SaveMapRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SaveMapRequest_

typedef ::vizanti::SaveMapRequest_<std::allocator<void> > SaveMapRequest;

typedef boost::shared_ptr< ::vizanti::SaveMapRequest > SaveMapRequestPtr;
typedef boost::shared_ptr< ::vizanti::SaveMapRequest const> SaveMapRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vizanti::SaveMapRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vizanti::SaveMapRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vizanti::SaveMapRequest_<ContainerAllocator1> & lhs, const ::vizanti::SaveMapRequest_<ContainerAllocator2> & rhs)
{
  return lhs.file_path == rhs.file_path &&
    lhs.topic == rhs.topic;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vizanti::SaveMapRequest_<ContainerAllocator1> & lhs, const ::vizanti::SaveMapRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vizanti

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vizanti::SaveMapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vizanti::SaveMapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vizanti::SaveMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vizanti::SaveMapRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vizanti::SaveMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vizanti::SaveMapRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vizanti::SaveMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9d37da9ab32bb82127946f0383b3d40b";
  }

  static const char* value(const ::vizanti::SaveMapRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9d37da9ab32bb821ULL;
  static const uint64_t static_value2 = 0x27946f0383b3d40bULL;
};

template<class ContainerAllocator>
struct DataType< ::vizanti::SaveMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vizanti/SaveMapRequest";
  }

  static const char* value(const ::vizanti::SaveMapRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vizanti::SaveMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string file_path\n"
"string topic\n"
;
  }

  static const char* value(const ::vizanti::SaveMapRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vizanti::SaveMapRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.file_path);
      stream.next(m.topic);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaveMapRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vizanti::SaveMapRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vizanti::SaveMapRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "file_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.file_path);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "topic: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.topic);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VIZANTI_MESSAGE_SAVEMAPREQUEST_H
