// Generated by gencpp from file vizanti/SaveMap.msg
// DO NOT EDIT!


#ifndef VIZANTI_MESSAGE_SAVEMAP_H
#define VIZANTI_MESSAGE_SAVEMAP_H

#include <ros/service_traits.h>


#include <vizanti/SaveMapRequest.h>
#include <vizanti/SaveMapResponse.h>


namespace vizanti
{

struct SaveMap
{

typedef SaveMapRequest Request;
typedef SaveMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveMap
} // namespace vizanti


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vizanti::SaveMap > {
  static const char* value()
  {
    return "46e31fc20e6d3bc78598163aa51c13bd";
  }

  static const char* value(const ::vizanti::SaveMap&) { return value(); }
};

template<>
struct DataType< ::vizanti::SaveMap > {
  static const char* value()
  {
    return "vizanti/SaveMap";
  }

  static const char* value(const ::vizanti::SaveMap&) { return value(); }
};


// service_traits::MD5Sum< ::vizanti::SaveMapRequest> should match
// service_traits::MD5Sum< ::vizanti::SaveMap >
template<>
struct MD5Sum< ::vizanti::SaveMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vizanti::SaveMap >::value();
  }
  static const char* value(const ::vizanti::SaveMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vizanti::SaveMapRequest> should match
// service_traits::DataType< ::vizanti::SaveMap >
template<>
struct DataType< ::vizanti::SaveMapRequest>
{
  static const char* value()
  {
    return DataType< ::vizanti::SaveMap >::value();
  }
  static const char* value(const ::vizanti::SaveMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vizanti::SaveMapResponse> should match
// service_traits::MD5Sum< ::vizanti::SaveMap >
template<>
struct MD5Sum< ::vizanti::SaveMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vizanti::SaveMap >::value();
  }
  static const char* value(const ::vizanti::SaveMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vizanti::SaveMapResponse> should match
// service_traits::DataType< ::vizanti::SaveMap >
template<>
struct DataType< ::vizanti::SaveMapResponse>
{
  static const char* value()
  {
    return DataType< ::vizanti::SaveMap >::value();
  }
  static const char* value(const ::vizanti::SaveMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VIZANTI_MESSAGE_SAVEMAP_H
