# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from warehouse_sorting_msgs/Cargo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class Cargo(genpy.Message):
  _md5sum = "f165e9d8fad2d5fab3540432824f5105"
  _type = "warehouse_sorting_msgs/Cargo"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string cargo_id
string cargo_type
geometry_msgs/Pose pose
geometry_msgs/Vector3 size
float32 volume
float32 confidence
int32 bbox_x
int32 bbox_y
int32 bbox_width
int32 bbox_height

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['cargo_id','cargo_type','pose','size','volume','confidence','bbox_x','bbox_y','bbox_width','bbox_height']
  _slot_types = ['string','string','geometry_msgs/Pose','geometry_msgs/Vector3','float32','float32','int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       cargo_id,cargo_type,pose,size,volume,confidence,bbox_x,bbox_y,bbox_width,bbox_height

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Cargo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.cargo_id is None:
        self.cargo_id = ''
      if self.cargo_type is None:
        self.cargo_type = ''
      if self.pose is None:
        self.pose = geometry_msgs.msg.Pose()
      if self.size is None:
        self.size = geometry_msgs.msg.Vector3()
      if self.volume is None:
        self.volume = 0.
      if self.confidence is None:
        self.confidence = 0.
      if self.bbox_x is None:
        self.bbox_x = 0
      if self.bbox_y is None:
        self.bbox_y = 0
      if self.bbox_width is None:
        self.bbox_width = 0
      if self.bbox_height is None:
        self.bbox_height = 0
    else:
      self.cargo_id = ''
      self.cargo_type = ''
      self.pose = geometry_msgs.msg.Pose()
      self.size = geometry_msgs.msg.Vector3()
      self.volume = 0.
      self.confidence = 0.
      self.bbox_x = 0
      self.bbox_y = 0
      self.bbox_width = 0
      self.bbox_height = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.cargo_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.cargo_type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_10d2f4i().pack(_x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.orientation.x, _x.pose.orientation.y, _x.pose.orientation.z, _x.pose.orientation.w, _x.size.x, _x.size.y, _x.size.z, _x.volume, _x.confidence, _x.bbox_x, _x.bbox_y, _x.bbox_width, _x.bbox_height))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pose is None:
        self.pose = geometry_msgs.msg.Pose()
      if self.size is None:
        self.size = geometry_msgs.msg.Vector3()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.cargo_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.cargo_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.cargo_type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.cargo_type = str[start:end]
      _x = self
      start = end
      end += 104
      (_x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.orientation.x, _x.pose.orientation.y, _x.pose.orientation.z, _x.pose.orientation.w, _x.size.x, _x.size.y, _x.size.z, _x.volume, _x.confidence, _x.bbox_x, _x.bbox_y, _x.bbox_width, _x.bbox_height,) = _get_struct_10d2f4i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.cargo_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.cargo_type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_10d2f4i().pack(_x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.orientation.x, _x.pose.orientation.y, _x.pose.orientation.z, _x.pose.orientation.w, _x.size.x, _x.size.y, _x.size.z, _x.volume, _x.confidence, _x.bbox_x, _x.bbox_y, _x.bbox_width, _x.bbox_height))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pose is None:
        self.pose = geometry_msgs.msg.Pose()
      if self.size is None:
        self.size = geometry_msgs.msg.Vector3()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.cargo_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.cargo_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.cargo_type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.cargo_type = str[start:end]
      _x = self
      start = end
      end += 104
      (_x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.orientation.x, _x.pose.orientation.y, _x.pose.orientation.z, _x.pose.orientation.w, _x.size.x, _x.size.y, _x.size.z, _x.volume, _x.confidence, _x.bbox_x, _x.bbox_y, _x.bbox_width, _x.bbox_height,) = _get_struct_10d2f4i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_10d2f4i = None
def _get_struct_10d2f4i():
    global _struct_10d2f4i
    if _struct_10d2f4i is None:
        _struct_10d2f4i = struct.Struct("<10d2f4i")
    return _struct_10d2f4i
