// Generated by gencpp from file fetch_server/Fetch.msg
// DO NOT EDIT!


#ifndef FETCH_SERVER_MESSAGE_FETCH_H
#define FETCH_SERVER_MESSAGE_FETCH_H

#include <ros/service_traits.h>


#include <fetch_server/FetchRequest.h>
#include <fetch_server/FetchResponse.h>


namespace fetch_server
{

struct Fetch
{

typedef FetchRequest Request;
typedef FetchResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Fetch
} // namespace fetch_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fetch_server::Fetch > {
  static const char* value()
  {
    return "88a1ffde7893c12d1c785f9936a31695";
  }

  static const char* value(const ::fetch_server::Fetch&) { return value(); }
};

template<>
struct DataType< ::fetch_server::Fetch > {
  static const char* value()
  {
    return "fetch_server/Fetch";
  }

  static const char* value(const ::fetch_server::Fetch&) { return value(); }
};


// service_traits::MD5Sum< ::fetch_server::FetchRequest> should match
// service_traits::MD5Sum< ::fetch_server::Fetch >
template<>
struct MD5Sum< ::fetch_server::FetchRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fetch_server::Fetch >::value();
  }
  static const char* value(const ::fetch_server::FetchRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fetch_server::FetchRequest> should match
// service_traits::DataType< ::fetch_server::Fetch >
template<>
struct DataType< ::fetch_server::FetchRequest>
{
  static const char* value()
  {
    return DataType< ::fetch_server::Fetch >::value();
  }
  static const char* value(const ::fetch_server::FetchRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fetch_server::FetchResponse> should match
// service_traits::MD5Sum< ::fetch_server::Fetch >
template<>
struct MD5Sum< ::fetch_server::FetchResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fetch_server::Fetch >::value();
  }
  static const char* value(const ::fetch_server::FetchResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fetch_server::FetchResponse> should match
// service_traits::DataType< ::fetch_server::Fetch >
template<>
struct DataType< ::fetch_server::FetchResponse>
{
  static const char* value()
  {
    return DataType< ::fetch_server::Fetch >::value();
  }
  static const char* value(const ::fetch_server::FetchResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FETCH_SERVER_MESSAGE_FETCH_H
