// Generated by gencpp from file fetch_server/FetchRequest.msg
// DO NOT EDIT!


#ifndef FETCH_SERVER_MESSAGE_FETCHREQUEST_H
#define FETCH_SERVER_MESSAGE_FETCHREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fetch_server
{
template <class ContainerAllocator>
struct FetchRequest_
{
  typedef FetchRequest_<ContainerAllocator> Type;

  FetchRequest_()
    : gpx(0.0)
    , gpy(0.0)
    , gpz(0.0)
    , goz(0.0)
    , ppx(0.0)
    , ppy(0.0)
    , ppz(0.0)
    , poz(0.0)  {
    }
  FetchRequest_(const ContainerAllocator& _alloc)
    : gpx(0.0)
    , gpy(0.0)
    , gpz(0.0)
    , goz(0.0)
    , ppx(0.0)
    , ppy(0.0)
    , ppz(0.0)
    , poz(0.0)  {
  (void)_alloc;
    }



   typedef double _gpx_type;
  _gpx_type gpx;

   typedef double _gpy_type;
  _gpy_type gpy;

   typedef double _gpz_type;
  _gpz_type gpz;

   typedef double _goz_type;
  _goz_type goz;

   typedef double _ppx_type;
  _ppx_type ppx;

   typedef double _ppy_type;
  _ppy_type ppy;

   typedef double _ppz_type;
  _ppz_type ppz;

   typedef double _poz_type;
  _poz_type poz;





  typedef boost::shared_ptr< ::fetch_server::FetchRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fetch_server::FetchRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FetchRequest_

typedef ::fetch_server::FetchRequest_<std::allocator<void> > FetchRequest;

typedef boost::shared_ptr< ::fetch_server::FetchRequest > FetchRequestPtr;
typedef boost::shared_ptr< ::fetch_server::FetchRequest const> FetchRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fetch_server::FetchRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fetch_server::FetchRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fetch_server::FetchRequest_<ContainerAllocator1> & lhs, const ::fetch_server::FetchRequest_<ContainerAllocator2> & rhs)
{
  return lhs.gpx == rhs.gpx &&
    lhs.gpy == rhs.gpy &&
    lhs.gpz == rhs.gpz &&
    lhs.goz == rhs.goz &&
    lhs.ppx == rhs.ppx &&
    lhs.ppy == rhs.ppy &&
    lhs.ppz == rhs.ppz &&
    lhs.poz == rhs.poz;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fetch_server::FetchRequest_<ContainerAllocator1> & lhs, const ::fetch_server::FetchRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fetch_server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fetch_server::FetchRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fetch_server::FetchRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fetch_server::FetchRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fetch_server::FetchRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fetch_server::FetchRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fetch_server::FetchRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fetch_server::FetchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a4e572a55a03d78b6a81f4cfe0a115e3";
  }

  static const char* value(const ::fetch_server::FetchRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa4e572a55a03d78bULL;
  static const uint64_t static_value2 = 0x6a81f4cfe0a115e3ULL;
};

template<class ContainerAllocator>
struct DataType< ::fetch_server::FetchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fetch_server/FetchRequest";
  }

  static const char* value(const ::fetch_server::FetchRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fetch_server::FetchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 gpx\n"
"float64 gpy\n"
"float64 gpz\n"
"float64 goz\n"
"float64 ppx\n"
"float64 ppy\n"
"float64 ppz\n"
"float64 poz\n"
;
  }

  static const char* value(const ::fetch_server::FetchRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fetch_server::FetchRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gpx);
      stream.next(m.gpy);
      stream.next(m.gpz);
      stream.next(m.goz);
      stream.next(m.ppx);
      stream.next(m.ppy);
      stream.next(m.ppz);
      stream.next(m.poz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FetchRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fetch_server::FetchRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fetch_server::FetchRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "gpx: ";
    Printer<double>::stream(s, indent + "  ", v.gpx);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "gpy: ";
    Printer<double>::stream(s, indent + "  ", v.gpy);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "gpz: ";
    Printer<double>::stream(s, indent + "  ", v.gpz);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "goz: ";
    Printer<double>::stream(s, indent + "  ", v.goz);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ppx: ";
    Printer<double>::stream(s, indent + "  ", v.ppx);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ppy: ";
    Printer<double>::stream(s, indent + "  ", v.ppy);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ppz: ";
    Printer<double>::stream(s, indent + "  ", v.ppz);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "poz: ";
    Printer<double>::stream(s, indent + "  ", v.poz);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FETCH_SERVER_MESSAGE_FETCHREQUEST_H
